In [3]:
# === RESUME SETUP (run first) ===
import os

# After you've done "Add Data > Notebook Output Files" with your last saved version,
# set this to the mounted path. Leave as None for a totally fresh run.
PREV_RUN_DIR = "/kaggle/input/notebooks/mdsadmansamikhan/rog-ap" # e.g. "/kaggle/input/rog-ap-6"

os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"  # cuts CUDA OOM from fragmentation

if PREV_RUN_DIR and os.path.exists(PREV_RUN_DIR):
    print("Previous run found at:", PREV_RUN_DIR)
else:
    print("No previous run mounted — starting fresh, or PREV_RUN_DIR not set yet.")

Previous run found at: /kaggle/input/notebooks/mdsadmansamikhan/rog-ap

In [4]:
import torch
_torch_pin = f"torch=={torch.__version__.split('+')[0]}"
print("Keeping installed PyTorch:", _torch_pin)

# accelerate==0.33.0 caps numpy<2.0, which drags Kaggle's numpy back from 2.x
# to 1.26.4 -- but Kaggle's pandas wheel is built against numpy 2.x's C ABI,
# so that downgrade breaks pandas at import time ("numpy.dtype size changed").
# accelerate>=0.34 dropped that cap, so bump it and pin numpy explicitly so
# pip can't silently downgrade it again.
!pip install -q \
    --only-binary=transformers,tokenizers,peft,sentencepiece,accelerate,datasets,numpy,torch \
    "transformers==4.44.2" "tokenizers==0.19.1" "peft==0.12.0" \
    "sentencepiece==0.2.0" "accelerate==0.34.2" "datasets==2.20.0" \
    "numpy>=2.0,<2.1" "graph-walker==1.0.6" "{_torch_pin}"

Keeping installed PyTorch: torch==2.10.0
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 74.9 MB/s eta 0:00:00:00:010:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 97.4 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.4/296.4 kB 24.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 24.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 39.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 37.1 MB/s eta 0:00:00
  Building wheel for graph-walker (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
tpot 1.1.0 requires dill>=0.3.9, but you have dill 0.3.8 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.5.0 which is incompatible.

### Confirmation of the Packages

In [5]:
import transformers, tokenizers, networkx
print("transformers:", transformers.__version__)
print("tokenizers:", tokenizers.__version__)
print("networkx:", networkx.__version__)

transformers: 4.44.2
tokenizers: 0.19.1
networkx: 3.6.1

### Cloning official REPO

In [6]:
# (optional) from huggingface_hub import login; login(token="<your_hf_token>")
import os, sys

REPO_DIR = "/kaggle/working/reasoning-on-graphs"
if not os.path.exists(REPO_DIR):
    !git clone --depth 1 https://github.com/RManLuo/reasoning-on-graphs.git {REPO_DIR}

sys.path.append(os.path.join(REPO_DIR, "src"))

# RQ1
# Objective 1: Baseline Establishment

## RoG-WebQSP Baseline

### Config

In [7]:
N_QUESTIONS = 50          # Step 1 checklist: "50-100 questions, not the whole dataset"
DATASET_NAME = "rmanluo/RoG-webqsp"
SPLIT = "test"
MODEL_PATH = "rmanluo/RoG"   # official pre-trained RoG checkpoint (planning + reasoning, same model)
N_BEAM = 3                 # matches the paper's K=3 (Section 5.4) and scripts/planning.sh
OUTPUT_DIR = "/kaggle/working/step1_baseline"
os.makedirs(OUTPUT_DIR, exist_ok=True)

### Load Dataset Subset

In [8]:
from datasets import load_dataset

full_test = load_dataset(DATASET_NAME, split=SPLIT)
subset = full_test.select(range(min(N_QUESTIONS, len(full_test))))
print(f"Loaded {len(subset)} / {len(full_test)} WebQSP test questions")
print("Fields:", subset.column_names)
subset[0]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/900 [00:00<?, ?B/s]

data/train-00000-of-00002-d810a36ed97bc2(…):   0%|          | 0.00/154M [00:00<?, ?B/s]

data/train-00001-of-00002-e53244e71082a3(…):   0%|          | 0.00/155M [00:00<?, ?B/s]

data/validation-00000-of-00001-6ee6adc5b(…):   0%|          | 0.00/24.3M [00:00<?, ?B/s]

data/test-00000-of-00002-9ee8d68f7d951e1(…):   0%|          | 0.00/90.9M [00:00<?, ?B/s]

data/test-00001-of-00002-773a7b8213e159f(…):   0%|          | 0.00/93.2M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2826 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/246 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1628 [00:00<?, ? examples/s]

Loaded 50 / 1628 WebQSP test questions
Fields: ['id', 'question', 'answer', 'q_entity', 'a_entity', 'graph', 'choices']

{'id': 'WebQTest-0',
 'question': 'what does jamaican people speak',
 'answer': ['Jamaican English', 'Jamaican Creole English Language'],
 'q_entity': ['Jamaica'],
 'a_entity': ['Jamaican English', 'Jamaican Creole English Language'],
 'graph': [['Jamaica',
   'meteorology.cyclone_affected_area.cyclones',
   'Tropical Storm Keith'],
  ['Jamaica',
   'location.statistical_region.prevalence_of_undernourisment',
   'g.12tb6gh4f'],
  ['Latoya Greaves', 'olympics.olympic_athlete.country', 'm.0k8nh0b'],
  ['Jamaica',
   'location.statistical_region.electricity_consumption_per_capita',
   'm.0nf4wmg'],
  ['Hurricane Hilda',
   'meteorology.tropical_cyclone.affected_areas',
   'Yucatán Peninsula'],
  ['m.0wj6j0d',
   'sports.competitor_competition_relationship.tournament',
   '2013 World Championships in Athletics'],
  ['Jamaica',
   'location.statistical_region.market_cap_of_listed_companies_as_percent_of_gdp',
   'g.1hhc3gxpy'],
  ['Jamaica',
   'location.statistical_region.energy_use_per_capita',
   'm.0nf5r2r'],
  ['Guatemala', 'common.topic.notable_types', 'Country'],
  ['Honduras',
   'meteorology.cyclone_affected_area.cyclones',
   '1915 New Orleans hurricane'],
  ['m.0b64vht',
   'sports.competitor_competition_relationship.competition',
   "2009 World Championships in Athletics – Women's 100 metres"],
  ['Hurricane Flora',
   'meteorology.tropical_cyclone.affected_areas',
   'Bahamas'],
  ['Jamaica', 'sports.sport_country.athletic_performances', 'm.0b6562_'],
  ['Hurricane Gordon', 'common.topic.notable_types', 'Tropical Cyclone'],
  ['Hurricane Dean',
   'meteorology.tropical_cyclone.affected_areas',
   'Cayman Islands'],
  ['m.08nbh3h', 'olympics.olympic_medal_honor.medalist', 'Merlene Ottey'],
  ['Ocho Rios', 'location.location.contains', 'Dolphin Cove Jamaica'],
  ['Jamaica',
   'location.statistical_region.gdp_nominal_per_capita',
   'g.1hhc3xgmf'],
  ['2007 World Championships in Athletics',
   'sports.multi_event_tournament.athletic_performances',
   'm.0b653pf'],
  ['Jamaica',
   'location.statistical_region.consumer_price_index',
   'g.1hhc4czcy'],
  ['Jamaica', 'location.statistical_region.cpi_inflation_rate', 'g.1hhc3cl0q'],
  ['Jamaica',
   'location.statistical_region.debt_service_as_percent_of_trade_volume',
   'g.11b71xnb4k'],
  ['Capture of the William',
   'common.topic.notable_types',
   'Military Conflict'],
  ['Miss Gomez and the Brethren', 'common.topic.notable_types', 'Book'],
  ['Haiti',
   'meteorology.cyclone_affected_area.cyclones',
   'Tropical Storm Fay'],
  ['m.0kq83_w', 'olympics.olympic_medal_honor.country', 'Jamaica'],
  ['Jamaica', 'location.country.first_level_divisions', 'Saint Andrew Parish'],
  ['m.0b64tz3',
   'sports.competitor_competition_relationship.country',
   'Jamaica'],
  ['Jamaica',
   'meteorology.cyclone_affected_area.cyclones',
   'Tropical Storm Chantal'],
  ['Mississippi',
   'meteorology.cyclone_affected_area.cyclones',
   '1900 Galveston hurricane'],
  ['Jamaica', 'location.statistical_region.gdp_real', 'm.0hny8lh'],
  ['2015 CONCACAF U-20 Championship', 'common.topic.notable_types', 'Event'],
  ['Honduras', 'location.location.containedby', 'North America'],
  ['Jamaica',
   'location.statistical_region.merchandise_trade_percent_of_gdp',
   'g.1hhc3mxqk'],
  ['m.0k8ngzt',
   'olympics.olympic_athlete_affiliation.athlete',
   'Kimberly Williams'],
  ['Saint Andrew Parish',
   'base.aareas.schema.administrative_area.administrative_parent',
   'Jamaica'],
  ['Georgia',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Florence (1953)'],
  ['Jamaica',
   'location.statistical_region.debt_service_as_percent_of_trade_volume',
   'g.1hhc3yf98'],
  ['Pirates!', 'book.written_work.subjects', 'Jamaica'],
  ['m.05sqzmp',
   'olympics.olympic_medal_honor.olympics',
   '2008 Summer Olympics'],
  ['m.0knk_cp',
   'olympics.olympic_medal_honor.event',
   "Athletics at the 2012 Summer Olympics – Men's 200 metres"],
  ['m.07nwldg',
   'olympics.olympic_medal_honor.olympics',
   '1980 Summer Olympics'],
  ['Central America', 'location.location.contains', 'Honduras'],
  ['Jamaica',
   'location.statistical_region.agriculture_as_percent_of_gdp',
   'g.1hhc3cb_1'],
  ['Hurricane Dennis',
   'meteorology.tropical_cyclone.affected_areas',
   'Bahamas'],
  ['m.0k8nh99',
   'olympics.olympic_athlete_affiliation.athlete',
   'Novlene Williams-Mills'],
  ['m.0hny8sn',
   'measurement_unit.adjusted_money_value.adjustment_currency',
   'United States Dollar'],
  ['Turks and Caicos Islands',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Greta'],
  ['Jamaica', 'meteorology.cyclone_affected_area.cyclones', 'Hurricane Debby'],
  ['Jamaica',
   'location.statistical_region.internet_users_percent_population',
   'm.0nf8c_t'],
  ['Jamaica',
   'location.statistical_region.gdp_nominal_per_capita',
   'g.1hhc51py9'],
  ['Jamaica',
   'location.statistical_region.size_of_armed_forces',
   'g.1hhc53gt9'],
  ['Location', 'freebase.type_hints.included_types', 'Topic'],
  ['Don Quarrie', 'olympics.olympic_athlete.medals_won', 'm.07yjcyj'],
  ['Jamaica',
   'location.statistical_region.merchandise_trade_percent_of_gdp',
   'g.1hhc3p9bc'],
  ['Jamaica',
   'location.statistical_region.time_required_to_start_a_business',
   'g.1hhc50_wv'],
  ['Kemar Bailey-Cole',
   'sports.tournament_event_competitor.events_competed_in',
   'm.011dwpqz'],
  ['Simone Facey', 'people.person.place_of_birth', 'Manchester Parish'],
  ['m.066nmg4',
   'base.athletics.athletics_championships_competition_athlete_relationship.medal',
   'Bronze medal'],
  ['m.0nf5r1w',
   'measurement_unit.dated_kgoe.source',
   'Energy use per capita, World Development Indicators and Global Development Finance, World Bank'],
  ['Jamaica',
   'location.statistical_region.market_cap_of_listed_companies_as_percent_of_gdp',
   'g.1hhc3hsck'],
  ['Jamaica',
   'location.statistical_region.gni_per_capita_in_ppp_dollars',
   'm.0nf98j1'],
  ['Hurricane Flora', 'meteorology.tropical_cyclone.affected_areas', 'Cuba'],
  ['Wayne Blackwood', 'people.person.gender', 'Male'],
  ['Jamaica', 'sports.sport_country.athletic_performances', 'm.0wj61d4'],
  ['Edward Seaga', 'people.person.gender', 'Male'],
  ['Jamaica',
   'olympics.olympic_participating_country.olympics_participated_in',
   '2014 Winter Olympics'],
  ['Hurricane Cleo', 'meteorology.tropical_cyclone.affected_areas', 'Florida'],
  ['Jamaica',
   'location.statistical_region.foreign_direct_investment_net_inflows',
   'g.1hhc4y7k7'],
  ['Hurricane Wilma', 'meteorology.tropical_cyclone.affected_areas', 'Cuba'],
  ['m.04hb9xy', 'olympics.olympic_medal_honor.country', 'Jamaica'],
  ['m.0k8nhl0', 'olympics.olympic_athlete_affiliation.country', 'Jamaica'],
  ['m.0wj6j0d',
   'sports.competitor_competition_relationship.medal',
   'Bronze medal'],
  ['m.010fpx13',
   'government.government_position_held.basic_title',
   'Prime minister'],
  ['East Coast of the United States',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Noel'],
  ['Jamaica',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Charley'],
  ['Jamaica',
   'location.statistical_region.renewable_freshwater_per_capita',
   'g.1hhc3hsc_'],
  ['Jamaica',
   'location.statistical_region.official_development_assistance',
   'g.1hhc3y6j8'],
  ['Portland Parish', 'location.location.containedby', 'Jamaica'],
  ['Jamaican Ministry of Tourism and Sports',
   'government.government_agency.jurisdiction',
   'Jamaica'],
  ['Jamaica',
   'location.statistical_region.internet_users_percent_population',
   'g.1245zm62k'],
  ['Jamaica',
   'location.statistical_region.military_expenditure_percent_gdp',
   'm.0nfb4rl'],
  ['Jamaica', 'common.topic.webpage', 'm.09xwf60'],
  ['Jamaica',
   'location.statistical_region.merchandise_trade_percent_of_gdp',
   'g.11b71tmz6z'],
  ['Traves Smikle', 'people.person.nationality', 'Jamaica'],
  ['Jamaica', 'common.topic.webpage', 'm.0b486t9'],
  ['Windward Islands',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Allen'],
  ['Hurricane Paloma',
   'meteorology.tropical_cyclone.affected_areas',
   'Bahamas'],
  ['Jamaica',
   'location.statistical_region.gni_per_capita_in_ppp_dollars',
   'm.0nf98j9'],
  ['m.0k8nhbl', 'olympics.olympic_athlete_affiliation.country', 'Jamaica'],
  ['Jamaica',
   'location.statistical_region.high_tech_as_percent_of_manufactured_exports',
   'g.1hhc38hp4'],
  ['m.0k8ngqp',
   'olympics.olympic_athlete_affiliation.athlete',
   'Kemar Bailey-Cole'],
  ['Trelawny Parish', 'location.location.people_born_here', 'Lerone Clarke'],
  ['m.0hny8tv',
   'measurement_unit.adjusted_money_value.source',
   'World Bank, World Development Indicators'],
  ['Jamaica',
   'location.statistical_region.debt_service_as_percent_of_trade_volume',
   'g.1hhc4gdq1'],
  ['Asafa Powell',
   'sports.tournament_event_competitor.events_competed_in',
   'm.0b652s6'],
  ['1915 New Orleans hurricane',
   'common.topic.notable_types',
   'Tropical Cyclone'],
  ["Dunn's River Falls",
   'travel.tourist_attraction.near_travel_destination',
   'Negril'],
  ['m.011df36v',
   'sports.competitor_competition_relationship.competitors',
   'Kaliese Spencer'],
  ['Hurricane Florence (1953)',
   'meteorology.tropical_cyclone.affected_areas',
   'Cuba'],
  ['m.0k8ngm9',
   'olympics.olympic_athlete_affiliation.athlete',
   'Edino Steele'],
  ['Jamaica',
   'location.statistical_region.health_expenditure_as_percent_of_gdp',
   'g.1hhc3vxrq'],
  ['Jamaica', 'location.statistical_region.gni_in_ppp_dollars', 'm.0nfbzlp'],
  ['Westmoreland Parish',
   'location.location.people_born_here',
   'Winthrop Graham'],
  ['Hurricane Debby', 'meteorology.tropical_cyclone.affected_areas', 'Cuba'],
  ['Invasion of Jamaica', 'time.event.included_in_event', 'Anglo-Spanish War'],
  ['Cornwall County, Jamaica',
   'location.location.contains',
   'Saint Elizabeth Parish'],
  ['m.09xy04n',
   'common.webpage.resource',
   'So, you think you can play Biggie Smalls?'],
  ['Hurricane Fifi–Orlene',
   'meteorology.tropical_cyclone.affected_areas',
   'Nicaragua'],
  ['m.04hb9xy',
   'olympics.olympic_medal_honor.olympics',
   '2008 Summer Olympics'],
  ['Hurricane Lili',
   'meteorology.tropical_cyclone.tropical_cyclone_season',
   '2002 Atlantic hurricane season'],
  ['Jamaica',
   'fictional_universe.fictional_setting.fictional_characters_born_here',
   'Dee Jay'],
  ['m.0k8nhwl', 'olympics.olympic_athlete_affiliation.country', 'Jamaica'],
  ['Jamaica', 'olympics.olympic_participating_country.athletes', 'm.0k8nhxh'],
  ['Jamaica',
   'location.statistical_region.prevalence_of_undernourisment',
   'g.12tb6gb73'],
  ['m.078y2zh',
   'olympics.olympic_medal_honor.medalist',
   'Veronica Campbell-Brown'],
  ['m.0kq839p',
   'olympics.olympic_medal_honor.event',
   "Athletics at the 2012 Summer Olympics – Men's 200 metres"],
  ['m.0hny8mx',
   'measurement_unit.adjusted_money_value.adjustment_currency',
   'United States Dollar'],
  ['m.0nf5r6y',
   'measurement_unit.dated_kgoe.source',
   'Energy use per capita, World Development Indicators and Global Development Finance, World Bank'],
  ['Hurricane Noel',
   'meteorology.tropical_cyclone.affected_areas',
   'Puerto Rico'],
  ['Jamaica',
   'location.statistical_region.market_cap_of_listed_companies_as_percent_of_gdp',
   'g.1hhc3d2r5'],
  ['Jamaica', 'location.statistical_region.cpi_inflation_rate', 'g.1hhc4lp1d'],
  ['m.0kq839p', 'olympics.olympic_medal_honor.country', 'Jamaica'],
  ['m.0b658yx',
   'sports.competitor_competition_relationship.competitors',
   'Shericka Williams'],
  ['Portia Simpson-Miller', 'people.person.employment_history', 'm.04dryz_'],
  ['Hurricane Emily', 'meteorology.tropical_cyclone.affected_areas', 'Mexico'],
  ['Bermuda', 'meteorology.cyclone_affected_area.cyclones', 'Hurricane Cleo'],
  ['m.0hny8hp',
   'measurement_unit.adjusted_money_value.source',
   'World Bank, World Development Indicators'],
  ['Abeng', 'book.written_work.subjects', 'Jamaica'],
  ['Delloreen Ennis-London', 'people.person.nationality', 'Jamaica'],
  ['Westmoreland Parish', 'location.location.containedby', 'Jamaica'],
  ['Saint James Parish',
   'location.location.containedby',
   'Cornwall County, Jamaica'],
  ['Jamaica', 'meteorology.cyclone_affected_area.cyclones', 'Hurricane Abby'],
  ['Jamaica',
   'location.statistical_region.consumer_price_index',
   'g.1hhc3t8h9'],
  ['Jamaica', 'location.statistical_region.gdp_growth_rate', 'g.1245zj345'],
  ['Sovereign state',
   'base.aareas.schema.administrative_area_type.pertains_to',
   'Earth'],
  ['m.0k8ngbl',
   'olympics.olympic_athlete_affiliation.athlete',
   'Christine Day'],
  ['Hurricane Abby',
   'meteorology.tropical_cyclone.affected_areas',
   'Lesser Antilles'],
  ['Hurricane Dennis',
   'meteorology.tropical_cyclone.affected_areas',
   'Georgia'],
  ['m.0nf5q_x',
   'measurement_unit.dated_kgoe.source',
   'Energy use per capita, World Development Indicators and Global Development Finance, World Bank'],
  ['m.010fq06d',
   'government.government_position_held.office_holder',
   'Bruce Golding'],
  ['m.065v_gr',
   'olympics.olympic_athlete_affiliation.olympics',
   '2002 Winter Olympics'],
  ['Saint Ann Parish', 'location.location.people_born_here', 'Damar Forbes'],
  ['m.0hny8v3',
   'measurement_unit.adjusted_money_value.source',
   'World Bank, World Development Indicators'],
  ['Currency', 'freebase.type_hints.included_types', 'Topic'],
  ['m.0k8nhbl',
   'olympics.olympic_athlete_affiliation.olympics',
   'The London 2012 Summer Olympics'],
  ['Hurricane Iris', 'meteorology.tropical_cyclone.affected_areas', 'Mexico'],
  ['Jamaica',
   'location.statistical_region.electricity_consumption_per_capita',
   'g.1245zw9zk'],
  ['Jamaica',
   'location.statistical_region.health_expenditure_as_percent_of_gdp',
   'g.1hhc42w1k'],
  ['m.0nfbzmy',
   'measurement_unit.dated_money_value.source',
   'Gross National Income in PPP dollars, World Development Indicators and Global Development Finance, World Bank'],
  ['Jamaica',
   'location.statistical_region.gross_savings_as_percent_of_gdp',
   'g.1hhc3_ppv'],
  ['m.0k5nthz',
   'measurement_unit.dated_percentage.source',
   'World Bank, World Development Indicators, GDP Growth Rate'],
  ['Hurricane Paloma',
   'meteorology.tropical_cyclone.affected_areas',
   'Cayman Islands'],
  ['Jamaica',
   'location.statistical_region.gross_savings_as_percent_of_gdp',
   'g.1hhc4y7nz'],
  ['North America', 'location.location.containedby', 'Americas'],
  ['Ministry of Foreign Affairs and Foreign Trade',
   'common.topic.webpage',
   'm.0jx6jhx'],
  ['Jamaica',
   'location.statistical_region.energy_use_per_capita',
   'g.12460gjd7'],
  ['m.0b65514',
   'sports.competitor_competition_relationship.country',
   'Jamaica'],
  ['m.0nf98gh',
   'measurement_unit.dated_money_value.currency',
   'United States Dollar'],
  ['Martha Brae River', 'location.location.geolocation', 'm.0cxxjqt'],
  ['Jamaica',
   'location.statistical_region.labor_participation_rate',
   'g.1hhc3fgyn'],
  ['m.0nf5r6h',
   'measurement_unit.dated_kgoe.source',
   'Energy use per capita, World Development Indicators and Global Development Finance, World Bank'],
  ['Jamaican parish', 'freebase.type_hints.included_types', 'Topic'],
  ['2013 World Championships in Athletics',
   'sports.multi_event_tournament.competitions',
   "2013 World Championships in Athletics – Men's 100 metres"],
  ['m.0hny8s2',
   'measurement_unit.adjusted_money_value.source',
   'World Bank, World Development Indicators'],
  ['Jamaica Association of Local Government Officers',
   'common.topic.notable_for',
   'g.1259t_ygc'],
  ['Kill me gently, darling', 'common.topic.notable_for', 'g.1254yrdzb'],
  ['Jamaica',
   'meteorology.cyclone_affected_area.cyclones',
   '1915 New Orleans hurricane'],
  ['Hurricane Hazel',
   'meteorology.tropical_cyclone.affected_areas',
   'Grenada'],
  ['m.0nf5r4z',
   'measurement_unit.dated_kgoe.source',
   'Energy use per capita, World Development Indicators and Global Development Finance, World Bank'],
  ['Jamaica',
   'location.statistical_region.market_cap_of_listed_companies_as_percent_of_gdp',
   'g.1hhc4twtr'],
  ['1916 Texas hurricane',
   'meteorology.tropical_cyclone.affected_areas',
   'Jamaica'],
  ['m.0hny8gk',
   'measurement_unit.adjusted_money_value.source',
   'World Bank, World Development Indicators'],
  ['Jamaica', 'location.statistical_region.gdp_growth_rate', 'm.0k5nt29'],
  ['Louisiana',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Florence (1953)'],
  ['m.0nf98jt',
   'measurement_unit.dated_money_value.source',
   'GNI per capita in PPP dollars, World Development Indicators and Global Development Finance, World Bank'],
  ['Mexico',
   'olympics.olympic_participating_country.olympics_participated_in',
   '2014 Winter Olympics'],
  ['Jamaica', 'olympics.olympic_participating_country.athletes', 'm.0k8ngdz'],
  ['m.0hqg83f',
   'government.government_position_held.jurisdiction_of_office',
   'Jamaica'],
  ['Veronica Campbell-Brown',
   'sports.tournament_event_competitor.events_competed_in',
   'm.0b64vmn'],
  ['m.0nf5r61',
   'measurement_unit.dated_kgoe.source',
   'Energy use per capita, World Development Indicators and Global Development Finance, World Bank'],
  ['Jamaica',
   'location.statistical_region.gni_per_capita_in_ppp_dollars',
   'g.11b60tv_5j'],
  ['Korene Hinds', 'people.person.place_of_birth', 'Saint Catherine Parish'],
  ['Jamaica',
   'location.statistical_region.military_expenditure_percent_gdp',
   'g.124618cb9'],
  ['Jamaica',
   'location.statistical_region.electricity_consumption_per_capita',
   'g.1245_9w09'],
  ['Hurricane Anna',
   'meteorology.tropical_cyclone.affected_areas',
   'Honduras'],
  ['Jamaica',
   'base.aareas.schema.administrative_area.administrative_children',
   'Saint Catherine Parish'],
  ['Lesser Antilles', 'location.location.contains', 'Windward Islands'],
  ['Venezuela',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Gilbert'],
  ['Rosemarie Whyte', 'olympics.olympic_athlete.country', 'm.0k8nhbz'],
  ['m.0nf98k1',
   'measurement_unit.dated_money_value.currency',
   'United States Dollar'],
  ['Jamaica', 'book.book_subject.works', 'Slipstream'],
  ['Venezuela',
   'meteorology.cyclone_affected_area.cyclones',
   'Hurricane Anna'],
  ['Human Language', 'freebase.type_profile.strict_included_types', 'Topic'],
  ['P. J. Patterson', 'people.person.nationality', 'Jamaica'],
  ['Jamaica',
   'location.statistical_region.military_expenditure_percent_gdp',
   'm.0nfb4nd'],
  ['m.04gdzf4', 'olympics.olympic_medal_honor.country', 'Jamaica'],
  ['m.0k8nhb3',
   'olympics.olympic_athlete_affiliation.olympics',
   'The London 2012 Summer Olympics'],
  ['Jamaica',
   'location.statistical_region.gdp_nominal_per_capita',
   'g.1hhc3d367'],
  ['River', 'freebase.type_profile.strict_included_types', 'Topic'],
  ['Desnoes & Geddes Red Stripe Lager', 'common.topic.notable_types', 'Beer'],
  ['Jamaica',
   'location.statistical_region.gross_savings_as_percent_of_gdp',
   'g.1hhc4sp_l'],
  ['m.0k8ngc8',
   'olympics.olympic_athlete_affiliation.athlete',
   'Damar Forbes'],
  ['Jamaica',
   'location.statistical_region.brain_drain_percent',
   'g.1hhc54340'],
  ['Jamaica',
   'location.statistical_region.co2_emissions_per_capita',
   'g.1245_0sgt'],
  ['m.0kq839p',
   'olympics.olympic_medal_honor.olympics',
   'The London 2012 Summer Olympics'],
  ['m.0nf98hr',
   'measurement_unit.dated_money_value.source',
   'GNI per capita in PPP dollars, World Development Indicators and Global Development Finance, World Bank'],
  ['Jamaica', 'location.location.events', 'Battle of Rio Nuevo'],
  ['Manchester Parish',
   'location.location.people_born_here',
   'Michael Frater'],
  ['Jamaica', 'location.country.administrative_divisions', 'Hanover Parish'],
  ['Dominican Republic', 'location.location.containedby', 'Americas'],
  ['Lesser Antilles',
   'meteorology.cyclone_affected_area.cyclones',

### Load the model

In [9]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, use_fast=False, clean_up_tokenization_spaces=True)
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH, device_map="auto", torch_dtype=torch.float16)
model.eval()
print("Model loaded.")

tokenizer_config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/78.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/438 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/672 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/183 [00:00<?, ?B/s]

Model loaded.

### Decode Patch

In [10]:
_original_decode = tokenizer.decode  # stash pre-patch decode for later verification (Part 2)

import types

def _sp_decode(self, token_ids, skip_special_tokens=True, **kwargs):
    tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
    return self.sp_model.decode(tokens)

tokenizer.decode = types.MethodType(_sp_decode, tokenizer)
print("Patched tokenizer.decode to use sp_model.decode directly.")

Patched tokenizer.decode to use sp_model.decode directly.

### Diagnostic

In [11]:
# Diagnostic -- run with your CURRENT tokenizer, no reinstall needed
print("Tokenizer class:", type(tokenizer))
print("Has sp_model:", hasattr(tokenizer, "sp_model"))

test = "location.location.languages_spoken"
ids = tokenizer.encode(test, add_special_tokens=False)
tokens = tokenizer.convert_ids_to_tokens(ids)
print("tokens:", tokens)
print("tokenizer.decode():   ", repr(tokenizer.decode(ids, clean_up_tokenization_spaces=True)))

if hasattr(tokenizer, "sp_model"):
    print("sp_model.decode() direct:", repr(tokenizer.sp_model.decode(tokens)))

Tokenizer class: <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>
Has sp_model: True
tokens: ['▁location', '.', 'location', '.', 'l', 'anguages', '_', 'sp', 'oken']
tokenizer.decode():    ' location.location.languages_spoken'
sp_model.decode() direct: ' location.location.languages_spoken'

### Importing official planning functions

In [12]:
from utils.utils import InstructFormater
from qa_prediction.gen_rule_path import generate_seq, parse_prediction, INSTRUCTION

prompter = InstructFormater(os.path.join(REPO_DIR, "prompts", "llama2.txt"))
print("Planning instruction:", repr(INSTRUCTION))

Planning instruction: 'Please generate a valid relation path that can be helpful for answering the following question: '

### Run Planning (relation-path generation)

In [13]:
import time, json
from tqdm.auto import tqdm

planning_records = []
for sample in tqdm(subset, desc="Planning"):
    input_text = prompter.format(instruction=INSTRUCTION, message=sample["question"])
    t0 = time.time()
    raw_output = generate_seq(model, input_text, tokenizer, num_beam=N_BEAM, do_sample=True, max_new_tokens=100)
    planning_time = time.time() - t0
    rel_paths = parse_prediction(raw_output["paths"])   # top-N_BEAM predicted relation paths
    planning_records.append({
        "id": sample["id"],
        "question": sample["question"],
        "q_entity": sample["q_entity"],
        "a_entity": sample["a_entity"],
        "graph": sample["graph"],
        "predicted_paths": rel_paths,
        "planning_time_sec": planning_time,
    })

print(f"Generated relation-path plans for {len(planning_records)} questions.")
print("Example plan:", planning_records[0]["predicted_paths"])

Planning:   0%|          | 0/50 [00:00<?, ?it/s]

Generated relation-path plans for 50 questions.
Example plan: [['location.country.languages_spoken'], ['language.human_language.countries_spoken_in'], ['location.country.official_language']]

### Instrumented BFS Wrapper

In [14]:
# Adds READ-ONLY per-hop frontier counters. Does NOT change which nodes get
# expanded or pruned -- traversal order and the relation-match pruning rule
# are copied verbatim from src/utils/graph_utils.py.
from collections import deque
from utils.graph_utils import build_graph, bfs_with_rule   # the OFFICIAL, unmodified function

def bfs_with_rule_instrumented(graph, start_node, target_rule):
    result_paths = []
    hop_frontier = [0] * len(target_rule)   # entities admitted into the frontier at each hop
    queue = deque([(start_node, [])])
    while queue:
        current_node, current_path = queue.popleft()
        if len(current_path) == len(target_rule):
            result_paths.append(current_path)
        if len(current_path) < len(target_rule):
            if current_node not in graph:
                continue
            hop_idx = len(current_path)
            for neighbor in graph.neighbors(current_node):
                rel = graph[current_node][neighbor]["relation"]
                if rel != target_rule[hop_idx] or len(current_path) > len(target_rule):
                    continue
                queue.append((neighbor, current_path + [(current_node, rel, neighbor)]))
                hop_frontier[hop_idx] += 1
    return result_paths, hop_frontier

### Sanity check (Show 0 mismatches)

In [15]:
mismatches = 0
checked = 0
for rec in planning_records:
    graph = build_graph(rec["graph"])
    for entity in rec["q_entity"]:
        for rule in rec["predicted_paths"]:
            checked += 1
            official_result = bfs_with_rule(graph, entity, rule)
            instrumented_result, _ = bfs_with_rule_instrumented(graph, entity, rule)
            if official_result != instrumented_result:
                mismatches += 1

print(f"Checked {checked} (entity, relation-path) calls. Mismatches: {mismatches}")
assert mismatches == 0, "Instrumented BFS diverges from official RoG retrieval -- STOP, do not trust downstream numbers."

Checked 150 (entity, relation-path) calls. Mismatches: 0

### Running Retrieval

In [16]:
def path_endpoints(paths):
    return set(p[-1][-1] for p in paths if len(p) > 0)

retrieval_records = []
for rec in tqdm(planning_records, desc="Retrieval"):
    graph = build_graph(rec["graph"])
    gold_answers = set(rec["a_entity"])
    plans = rec["predicted_paths"] if len(rec["predicted_paths"]) > 0 else [[]]
    for rule in plans:
        t0 = time.time()
        all_paths = []
        hop_frontier_total = [0] * len(rule)
        if len(rule) > 0:
            for entity in rec["q_entity"]:
                paths, hop_frontier = bfs_with_rule_instrumented(graph, entity, rule)
                all_paths.extend(paths)
                for h in range(len(rule)):
                    hop_frontier_total[h] += hop_frontier[h]
        retrieval_time = time.time() - t0
        reachable_gold = sorted(path_endpoints(all_paths) & gold_answers)
        retrieval_records.append({
            "question_id": rec["id"],
            "question": rec["question"],
            "topic_entity": rec["q_entity"],
            "predicted_relation_path": rule,
            "hop_frontiers": hop_frontier_total,   # [hop_1_frontier, hop_2_frontier, ...]
            "retrieved_paths_count": len(all_paths),
            "gold_answers": sorted(gold_answers),
            "reachable_gold_answers": reachable_gold,
            "gold_reachable": len(reachable_gold) > 0,
            "retrieval_time_sec": retrieval_time,
            "planning_time_sec": rec["planning_time_sec"],
        })

print(f"{len(retrieval_records)} (question, relation-plan) retrieval records collected.")

Retrieval:   0%|          | 0/50 [00:00<?, ?it/s]

147 (question, relation-plan) retrieval records collected.

### Question Evaluation

In [17]:
import pandas as pd
df = pd.DataFrame(retrieval_records)

question_coverage = (
    df.groupby("question_id")["gold_reachable"]
      .any()
)

print("Questions evaluated:", len(question_coverage))
print("Questions reaching at least one gold answer:", question_coverage.sum())
print("Question-level retrieval coverage:",
      question_coverage.mean() * 100)

Questions evaluated: 50
Questions reaching at least one gold answer: 38
Question-level retrieval coverage: 76.0

### Computing missed_qids

In [18]:
from collections import defaultdict

reachable_by_question = defaultdict(bool)
for rec in retrieval_records:
    reachable_by_question[rec["question_id"]] |= rec["gold_reachable"]

all_qids = {rec["question_id"] for rec in retrieval_records}
missed_qids = [qid for qid in all_qids if not reachable_by_question[qid]]

print(f"{len(missed_qids)} / {len(all_qids)} questions missed")

12 / 50 questions missed

### Revised Failure Analysis

In [19]:
from collections import deque

def find_gold_paths_official_graph(rec, max_hops=2):
    G = build_graph(rec["graph"])
    gold = set(rec["a_entity"])
    found = []

    for start in rec["q_entity"]:
        queue = deque([(start, [], [start])])

        while queue:
            node, relations, entities = queue.popleft()

            if len(relations) > 0 and node in gold:
                found.append({
                    "relations": relations,
                    "entities": entities
                })

            if len(relations) == max_hops:
                continue

            if node not in G:
                continue

            for neighbor in G.neighbors(node):
                rel = G[node][neighbor]["relation"]

                queue.append((
                    neighbor,
                    relations + [rel],
                    entities + [neighbor]
                ))

    return found

for qid in missed_qids:

    rec = next(r for r in planning_records if r["id"] == qid)

    gold_paths = find_gold_paths_official_graph(rec, max_hops=2)

    predicted = {
        tuple(p) for p in rec["predicted_paths"]
    }

    gold_relation_paths = {
        tuple(p["relations"]) for p in gold_paths
    }

    print("\n" + "="*100)
    print("QUESTION:", rec["question"])
    print("GOLD:", rec["a_entity"])

    print("\nPredicted:")
    for p in predicted:
        print(" ", " -> ".join(p))

    print("\nGold-supporting paths in OFFICIAL BUILT GRAPH:")
    for p in gold_paths[:10]:
        print(
            " ",
            " -> ".join(p["entities"]),
            "\n    ",
            " -> ".join(p["relations"])
        )

    if not gold_paths:
        diagnosis = "OFFICIAL GRAPH COVERAGE FAILURE"

    elif predicted.isdisjoint(gold_relation_paths):
        diagnosis = "PLANNER FAILURE"

    else:
        diagnosis = "TRUE RETRIEVAL ANOMALY"

    print("\nDIAGNOSIS:", diagnosis)

====================================================================================================
QUESTION: who plays ken barlow in coronation street
GOLD: ['William Roache']

Predicted:
  tv.tv_program.country_of_origin -> people.person.nationality
  tv.regular_tv_appearance.series -> tv.regular_tv_appearance.actor
  tv.regular_tv_appearance.series -> tv.tv_actor.starring_roles

Gold-supporting paths in OFFICIAL BUILT GRAPH:

DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: who is governor of ohio 2011
GOLD: ['John Kasich', 'Ted Strickland', 'Return J. Meigs, Jr.']

Predicted:
  government.governmental_jurisdiction.governing_officials -> government.government_position_held.office_holder
  government.government_position_held.jurisdiction_of_office -> government.government_position_held.office_holder
  government.governmental_jurisdiction.governing_officials -> government.politician.government_positions_held

Gold-supporting paths in OFFICIAL BUILT GRAPH:
  Ohio -> United States of America -> Return J. Meigs, Jr.
     base.locations.states_and_provences.country -> people.person.nationality
  Ohio -> m.0bfmhy4 -> Return J. Meigs, Jr.
     government.political_district.representatives -> government.politician.government_positions_held

DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: what highschool did harper lee go to
GOLD: ['Monroe County High School']

Predicted:
  people.person.education -> education.educational_institution.students_graduates
  education.education.student -> education.education.institution
  people.person.education -> education.education.institution

Gold-supporting paths in OFFICIAL BUILT GRAPH:
  Harper Lee -> m.0lwxmyl -> Monroe County High School
     education.education.student -> education.educational_institution.students_graduates

DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: where did andy murray started playing tennis
GOLD: ['2005']

Predicted:
  sports.sports_facility.teams
  people.person.nationality -> location.location.containedby
  sports.sports_facility.athlete -> sports.sports_facility.location

Gold-supporting paths in OFFICIAL BUILT GRAPH:

DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: when did annie open
GOLD: ['1976-08-10']

Predicted:
  theater.theater_character.plays_appears_in
  theater.play.characters
  film.film.directed_by

Gold-supporting paths in OFFICIAL BUILT GRAPH:

DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: what is the australian dollar called
GOLD: ['AUD']

Predicted:
  finance.currency.countries_used
  location.country.currency_used
  location.country.currency_used -> common.topic.notable_types -> common.topic.notable_types

Gold-supporting paths in OFFICIAL BUILT GRAPH:

DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: what electorate does anna bligh represent
GOLD: ['Electoral district of South Brisbane']

Predicted:
  government.government_position_held.office_holder -> government.government_position_held.district_represented
  government.politician.government_positions_held -> government.government_position_held.district_represented
  people.person.nationality -> base.biblioness.bibs_location.country

Gold-supporting paths in OFFICIAL BUILT GRAPH:
  Anna Bligh -> m.0cr320w -> Electoral district of South Brisbane
     government.politician.government_positions_held -> government.political_district.representatives

DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: who did george w. bush run against for the second term
GOLD: ['John Kerry', 'Ralph Nader', 'Michael Peroutka', 'Gene Amondson']

Predicted:
  common.topic.image -> common.image.appears_in_topic_gallery
  government.election.campaigns -> government.election_campaign.candidate
  time.event.locations -> people.person.nationality

Gold-supporting paths in OFFICIAL BUILT GRAPH:

DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: who is niall ferguson 's wife
GOLD: ['Ayaan Hirsi Ali']

Predicted:
  freebase.valuenotation.is_reviewed -> freebase.valuenotation.has_value
  freebase.valuenotation.is_reviewed -> freebase.valuenotation.is_reviewed
  people.person.nationality -> people.person.nationality

Gold-supporting paths in OFFICIAL BUILT GRAPH:
  Niall Ferguson -> m.0j4jq57 -> Ayaan Hirsi Ali
     people.person.spouse_s -> people.person.spouse_s
  Niall Ferguson -> Thomas Ferguson -> Ayaan Hirsi Ali
     people.person.children -> people.person.children
  Niall Ferguson -> Parents -> Ayaan Hirsi Ali
     freebase.valuenotation.has_value -> freebase.valuenotation.is_reviewed
  Niall Ferguson -> Author -> Ayaan Hirsi Ali
     people.person.profession -> common.topic.notable_types
  Niall Ferguson -> Writer -> Ayaan Hirsi Ali
     people.person.profession -> people.person.profession

DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: who did cam newton sign with
GOLD: ['Carolina Panthers']

Predicted:
  american_football.player_rushing_statistics.player -> american_football.player_rushing_statistics.team
  american_football.football_player.games -> american_football.player_game_statistics.team
  american_football.football_player.rushing -> american_football.player_rushing_statistics.team

Gold-supporting paths in OFFICIAL BUILT GRAPH:
  Cam Newton -> m.0j37n7l -> Carolina Panthers
     base.schemastaging.athlete_extra.salary -> base.schemastaging.athlete_salary.team
  Cam Newton -> m.010dqbnl -> Carolina Panthers
     base.schemastaging.athlete_salary.athlete -> base.schemastaging.athlete_salary.team
  Cam Newton -> m.04nb7yn -> Carolina Panthers
     sports.pro_athlete.teams -> sports.sports_team_roster.team

DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: what year did president william henry harrison take office
GOLD: ['1841-03-04']

Predicted:
  government.election_campaign.candidate -> time.event.instance_of_recurring_event
  government.election_campaign.candidate -> time.event.locations
  government.election_campaign.candidate -> government.election_campaign.election

Gold-supporting paths in OFFICIAL BUILT GRAPH:

DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: who was richard nixon married to
GOLD: ['Pat Nixon']

Predicted:
  freebase.valuenotation.is_reviewed -> freebase.valuenotation.is_reviewed
  freebase.valuenotation.is_reviewed -> freebase.valuenotation.has_value
  people.person.parents -> people.person.parents

Gold-supporting paths in OFFICIAL BUILT GRAPH:
  Richard Nixon -> m.05hqqz6 -> Pat Nixon
     base.famouspets.pet_owner.pets_owned -> base.famouspets.pet_owner.pets_owned
  Richard Nixon -> m.05hqn27 -> Pat Nixon
     base.famouspets.pet_owner.pets_owned -> base.famouspets.pet_owner.pets_owned
  Richard Nixon -> m.02h98gq -> Pat Nixon
     people.person.spouse_s -> people.person.spouse_s
  Richard Nixon -> United States of America -> Pat Nixon
     people.person.nationality -> people.person.nationality
  Richard Nixon -> Politician -> Pat Nixon
     people.person.profession -> common.topic.notable_types
  Richard Nixon -> Julie Nixon Eisenhower -> Pat Nixon
     people.person.children -> people.person.parents
  Richard Nixon -> Tricia Nixon Cox -> Pat Nixon
     people.person.children -> people.person.parents
  Richard Nixon -> m.05hqld4 -> Pat Nixon
     base.famouspets.pet_ownership.owner -> base.famouspets.pet_ownership.owner
  Richard Nixon -> m.05hqnyc -> Pat Nixon
     base.famouspets.pet_owner.pets_owned -> base.famouspets.pet_ownership.owner

DIAGNOSIS: PLANNER FAILURE

### JSON, CSV save

In [20]:
import pandas as pd

json_path = os.path.join(OUTPUT_DIR, "step1_baseline_webqsp.json")
csv_path = os.path.join(OUTPUT_DIR, "step1_baseline_webqsp.csv")

with open(json_path, "w") as f:
    json.dump(retrieval_records, f, indent=2)

df = pd.DataFrame(retrieval_records)
df.to_csv(csv_path, index=False)

print("Saved:", json_path)
print("Saved:", csv_path)
df[["retrieved_paths_count", "gold_reachable", "retrieval_time_sec"]].describe()

Saved: /kaggle/working/step1_baseline/step1_baseline_webqsp.json
Saved: /kaggle/working/step1_baseline/step1_baseline_webqsp.csv

       retrieved_paths_count  retrieval_time_sec
count             147.000000          147.000000
mean                6.564626            0.000197
std                27.793531            0.000231
min                 0.000000            0.000007
25%                 0.000000            0.000056
50%                 1.000000            0.000141
75%                 3.000000            0.000217
max               320.000000            0.001233

### Worked Example

In [21]:
example = next(r for r in retrieval_records if len(r["predicted_relation_path"]) > 0)

print("Question:")
print(example["question"])
print()
print("Topic entity:")
print(example["topic_entity"])
print()
print("RoG relation plan:")
print(" -> ".join(example["predicted_relation_path"]))
print()
for i, count in enumerate(example["hop_frontiers"], start=1):
    print(f"Hop {i}:")
    print(f"{count} candidate entities")
    print()
print("Retrieved paths:")
print(example["retrieved_paths_count"])
print()
print("Gold answer reachable:")
print("Yes" if example["gold_reachable"] else "No")
print()
print("Retrieval time:")
print(f"{example['retrieval_time_sec']*1000:.1f} ms")

Question:
what does jamaican people speak

Topic entity:
['Jamaica']

RoG relation plan:
location.country.languages_spoken

Hop 1:
1 candidate entities

Retrieved paths:
1

Gold answer reachable:
Yes

Retrieval time:
1.2 ms

### Final RoG Answer

In [22]:
from qa_prediction.build_qa_input import PromptBuilder

reasoning_prompter = PromptBuilder(
    os.path.join(REPO_DIR, "prompts", "llama2_predict.txt"),
    add_rule=True,
    maximun_token=4096 - 100,
    tokenize=lambda t: len(tokenizer.tokenize(t)),
)

by_question = {}
for rec in planning_records:
    by_question[rec["id"]] = rec

final_answers = {}
for qid, rec in tqdm(by_question.items(), desc="Reasoning"):
    q_dict = {
        "question": rec["question"],
        "graph": rec["graph"],
        "q_entity": rec["q_entity"],
        "predicted_paths": rec["predicted_paths"],
        "choices": [],
    }
    prompt = reasoning_prompter.process_input(q_dict)
    input_ids = tokenizer.encode(prompt, return_tensors="pt").to(model.device)
    t0 = time.time()
    with torch.inference_mode():
        out = model.generate(input_ids=input_ids, max_new_tokens=512, do_sample=True)
    gen_time = time.time() - t0
    text = tokenizer.decode(out[0][input_ids.shape[1]:], skip_special_tokens=True).strip()
    final_answers[qid] = {"final_RoG_answer": text, "reasoning_time_sec": gen_time}

for rec in retrieval_records:
    rec.update(final_answers.get(rec["question_id"], {}))

with open(json_path, "w") as f:
    json.dump(retrieval_records, f, indent=2)
pd.DataFrame(retrieval_records).to_csv(csv_path, index=False)
print("Updated with final_RoG_answer and re-saved.")

Reasoning:   0%|          | 0/50 [00:00<?, ?it/s]

Updated with final_RoG_answer and re-saved.

### Verify the Decode Patch(full set)

In [23]:
default_decode_records = []
for sample in tqdm(subset, desc="Verify (default decode)"):
    input_text = prompter.format(instruction=INSTRUCTION, message=sample["question"])
    input_ids = tokenizer.encode(input_text, return_tensors="pt").to(model.device)
    with torch.inference_mode():
        output = model.generate(
            input_ids=input_ids, num_beams=N_BEAM, num_return_sequences=N_BEAM,
            early_stopping=False, do_sample=True, return_dict_in_generate=True,
            output_scores=True, max_new_tokens=100,
        )
    raw_sequences = output.sequences[:, input_ids.shape[1]:]
    default_text = [_original_decode(seq, skip_special_tokens=True).strip() for seq in raw_sequences]
    default_paths = parse_prediction(default_text)
    default_decode_records.append({"id": sample["id"], "predicted_paths": default_paths})

by_id_default = {r["id"]: r["predicted_paths"] for r in default_decode_records}
diffs = 0
examples_shown = 0
for rec in planning_records:
    patched = rec["predicted_paths"]
    default = by_id_default.get(rec["id"], [])
    if patched != default:
        diffs += 1
        if examples_shown < 5:
            print(f"\nQID {rec['id']}  --  {rec['question']}")
            print("  patched (sp_model.decode): ", patched)
            print("  default (tokenizer.decode):", default)
            examples_shown += 1

print(f"\n{diffs} / {len(planning_records)} questions differ between patched and default decode.")
if diffs == 0:
    print("No difference on the pilot -- the patch is a safe no-op here; keep it for robustness.")
else:
    print("Inspect the examples above: genuine fix, or a new deviation? Decide before scaling.")

Verify (default decode):   0%|          | 0/50 [00:00<?, ?it/s]

0 / 50 questions differ between patched and default decode.
No difference on the pilot -- the patch is a safe no-op here; keep it for robustness.

### Runtime Estimate

In [24]:
df_pilot = pd.DataFrame(retrieval_records)
mean_plan = df_pilot["planning_time_sec"].mean()
mean_retr = df_pilot["retrieval_time_sec"].mean()
n_full = 1628  # official WebQSP test size (RoG paper, Table 6)

est_plan_sec = mean_plan * n_full
est_retr_sec = mean_retr * n_full
est_total_hr = (est_plan_sec + est_retr_sec) / 3600

print(f"Mean planning time/question:  {mean_plan:.2f} s")
print(f"Mean retrieval time/question: {mean_retr:.3f} s")
print(f"Projected for {n_full} questions:")
print(f"  Planning:  ~{est_plan_sec/60:.1f} min")
print(f"  Retrieval: ~{est_retr_sec/60:.1f} min")
print(f"  Total:     ~{est_total_hr:.2f} GPU-hours (planning+retrieval only, not the optional final-answer pass)")
print()
print("Kaggle sessions have historically capped continuous runtime around 9 hours,")
print("with a weekly GPU quota that's fluctuated between ~30 and ~40 hours. Check")
print("your account's current quota (Settings) -- it changes over time. The")
print("checkpointed loops below handle a session cutoff gracefully: just re-run")
print("the cell and it resumes from the last completed question.")

Mean planning time/question:  1.99 s
Mean retrieval time/question: 0.000 s
Projected for 1628 questions:
  Planning:  ~54.0 min
  Retrieval: ~0.0 min
  Total:     ~0.90 GPU-hours (planning+retrieval only, not the optional final-answer pass)

Kaggle sessions have historically capped continuous runtime around 9 hours,
with a weekly GPU quota that's fluctuated between ~30 and ~40 hours. Check
your account's current quota (Settings) -- it changes over time. The
checkpointed loops below handle a session cutoff gracefully: just re-run
the cell and it resumes from the last completed question.

### Full-scale Config

In [25]:
FULL_OUTPUT_DIR = "/kaggle/working/step1_baseline_full"
os.makedirs(FULL_OUTPUT_DIR, exist_ok=True)
# === RESTORE WebQSP checkpoints from last session ===
import shutil

if PREV_RUN_DIR:
    prev_dir = os.path.join(PREV_RUN_DIR, "step1_baseline_full")
    if os.path.exists(prev_dir):
        for fname in os.listdir(prev_dir):
            dst = os.path.join(FULL_OUTPUT_DIR, fname)
            if not os.path.exists(dst):
                shutil.copy2(os.path.join(prev_dir, fname), dst)
                print("Restored:", fname)
    else:
        print("No prior WebQSP full-run folder in PREV_RUN_DIR.")
else:
    print("PREV_RUN_DIR not set — nothing to restore.")

PLANNING_CKPT = os.path.join(FULL_OUTPUT_DIR, "planning_webqsp_full.jsonl")
REASON_CKPT = os.path.join(FULL_OUTPUT_DIR, "reasoning_webqsp_full.jsonl")

full_test_all = load_dataset(DATASET_NAME, split=SPLIT)  # all 1,628 WebQSP test questions
print(f"Full test set: {len(full_test_all)} questions")

Full test set: 1628 questions

### Checkpointed planning (full set)

In [26]:
def load_checkpoint(path):
    done = {}
    if os.path.exists(path):
        with open(path) as f:
            for line in f:
                if line.strip():
                    rec = json.loads(line)
                    done[rec["id"]] = rec
    return done

planning_done = load_checkpoint(PLANNING_CKPT)
print(f"Resuming: {len(planning_done)} questions already planned.")

with open(PLANNING_CKPT, "a") as fout:
    for sample in tqdm(full_test_all, desc="Planning (full)"):
        if sample["id"] in planning_done:
            continue
        input_text = prompter.format(instruction=INSTRUCTION, message=sample["question"])
        t0 = time.time()
        raw_output = generate_seq(model, input_text, tokenizer, num_beam=N_BEAM, do_sample=False, max_new_tokens=100)
        planning_time = time.time() - t0
        rel_paths = parse_prediction(raw_output["paths"])
        rec = {
            "id": sample["id"], "question": sample["question"],
            "q_entity": sample["q_entity"], "a_entity": sample["a_entity"],
            "graph": sample["graph"], "predicted_paths": rel_paths,
            "planning_time_sec": planning_time,
        }
        fout.write(json.dumps(rec) + "\n")
        fout.flush()
        planning_done[sample["id"]] = rec

planning_records_full = list(planning_done.values())
print(f"Planning complete: {len(planning_records_full)} / {len(full_test_all)} questions.")

Resuming: 1628 questions already planned.

Planning (full):   0%|          | 0/1628 [00:00<?, ?it/s]

Planning complete: 1628 / 1628 questions.

### Retrieval (Full set)

In [27]:
retrieval_records_full = []
for rec in tqdm(planning_records_full, desc="Retrieval (full)"):
    graph = build_graph(rec["graph"])
    gold_answers = set(rec["a_entity"])
    plans = rec["predicted_paths"] if len(rec["predicted_paths"]) > 0 else [[]]
    for rule in plans:
        t0 = time.time()
        all_paths = []
        hop_frontier_total = [0] * len(rule)
        if len(rule) > 0:
            for entity in rec["q_entity"]:
                paths, hop_frontier = bfs_with_rule_instrumented(graph, entity, rule)
                all_paths.extend(paths)
                for h in range(len(rule)):
                    hop_frontier_total[h] += hop_frontier[h]
        retrieval_time = time.time() - t0
        reachable_gold = sorted(path_endpoints(all_paths) & gold_answers)
        retrieval_records_full.append({
            "question_id": rec["id"], "question": rec["question"],
            "topic_entity": rec["q_entity"], "predicted_relation_path": rule,
            "hop_frontiers": hop_frontier_total,
            "retrieved_paths_count": len(all_paths),
            "gold_answers": sorted(gold_answers),
            "reachable_gold_answers": reachable_gold,
            "gold_reachable": len(reachable_gold) > 0,
            "retrieval_time_sec": retrieval_time,
            "planning_time_sec": rec["planning_time_sec"],
        })

print(f"{len(retrieval_records_full)} retrieval records (full set) collected.")

Retrieval (full):   0%|          | 0/1628 [00:00<?, ?it/s]

4838 retrieval records (full set) collected.

### Question-Level Coverage

In [28]:
df_full = pd.DataFrame(retrieval_records_full)
question_coverage_full = df_full.groupby("question_id")["gold_reachable"].any()
print("Questions evaluated:", len(question_coverage_full))
print("Questions reaching >=1 gold answer:", question_coverage_full.sum())
print("Question-level retrieval coverage: %.2f%%" % (question_coverage_full.mean() * 100))

Questions evaluated: 1628
Questions reaching >=1 gold answer: 1369
Question-level retrieval coverage: 84.09%

### Aggregated Failure Analysis

In [29]:
from collections import Counter

reachable_by_q_full = defaultdict(bool)
for rec in retrieval_records_full:
    reachable_by_q_full[rec["question_id"]] |= rec["gold_reachable"]

all_qids_full = {rec["question_id"] for rec in retrieval_records_full}
missed_qids_full = [q for q in all_qids_full if not reachable_by_q_full[q]]
print(f"{len(missed_qids_full)} / {len(all_qids_full)} questions missed")

planning_by_id_full = {r["id"]: r for r in planning_records_full}
diagnosis_counts = Counter()
diagnosis_by_qid = {}
SAMPLE_PRINT = 5
printed = 0

for qid in tqdm(missed_qids_full, desc="Failure analysis"):
    rec = planning_by_id_full[qid]
    gold_paths = find_gold_paths_official_graph(rec, max_hops=2)  # WebQSP max hop = 2 (Table 6); bump to 4 for CWQ later
    predicted = {tuple(p) for p in rec["predicted_paths"]}
    gold_relation_paths = {tuple(p["relations"]) for p in gold_paths}

    if not gold_paths:
        diagnosis = "OFFICIAL GRAPH COVERAGE FAILURE"
    elif predicted.isdisjoint(gold_relation_paths):
        diagnosis = "PLANNER FAILURE"
    else:
        diagnosis = "TRUE RETRIEVAL ANOMALY"

    diagnosis_counts[diagnosis] += 1
    diagnosis_by_qid[qid] = diagnosis

    if printed < SAMPLE_PRINT:
        print("\n" + "="*100)
        print("QUESTION:", rec["question"])
        print("DIAGNOSIS:", diagnosis)
        printed += 1

print("\n--- Failure breakdown ---")
for k, v in diagnosis_counts.most_common():
    print(f"{k}: {v}  ({100*v/max(len(missed_qids_full),1):.1f}% of missed questions)")

for rec in retrieval_records_full:
    rec["failure_diagnosis"] = diagnosis_by_qid.get(rec["question_id"])

259 / 1628 questions missed

Failure analysis:   0%|          | 0/259 [00:00<?, ?it/s]

====================================================================================================
QUESTION: when was the printing press invented by gutenberg
DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: what sarah dessen books are movies
DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: when was lucy lawless born
DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

====================================================================================================
QUESTION: who was selena gomez in barney and friends
DIAGNOSIS: PLANNER FAILURE

====================================================================================================
QUESTION: when did the burma cyclone happen
DIAGNOSIS: OFFICIAL GRAPH COVERAGE FAILURE

--- Failure breakdown ---
PLANNER FAILURE: 188  (72.6% of missed questions)
OFFICIAL GRAPH COVERAGE FAILURE: 71  (27.4% of missed questions)

### Full Scale Output

In [30]:
full_json_path = os.path.join(FULL_OUTPUT_DIR, "step1_baseline_webqsp_full.json")
full_csv_path = os.path.join(FULL_OUTPUT_DIR, "step1_baseline_webqsp_full.csv")

with open(full_json_path, "w") as f:
    json.dump(retrieval_records_full, f, indent=2)
pd.DataFrame(retrieval_records_full).to_csv(full_csv_path, index=False)
print("Saved:", full_json_path)
print("Saved:", full_csv_path)

Saved: /kaggle/working/step1_baseline_full/step1_baseline_webqsp_full.json
Saved: /kaggle/working/step1_baseline_full/step1_baseline_webqsp_full.csv

### Final RoG Answer (Full Planning)

In [31]:
reasoning_done = load_checkpoint(REASON_CKPT)
print(f"Resuming: {len(reasoning_done)} answers already generated.")

with open(REASON_CKPT, "a") as fout:
    for qid, rec in tqdm(planning_by_id_full.items(), desc="Reasoning (full)"):
        if qid in reasoning_done:
            continue
        q_dict = {
            "question": rec["question"], "graph": rec["graph"],
            "q_entity": rec["q_entity"], "predicted_paths": rec["predicted_paths"],
            "choices": [],
        }
        prompt = reasoning_prompter.process_input(q_dict)
        input_ids = tokenizer.encode(prompt, return_tensors="pt").to(model.device)
        t0 = time.time()
        with torch.inference_mode():
            out = model.generate(input_ids=input_ids, max_new_tokens=512, do_sample=True)
        gen_time = time.time() - t0
        text = tokenizer.decode(out[0][input_ids.shape[1]:], skip_special_tokens=True).strip()
        out_rec = {"id": qid, "final_RoG_answer": text, "reasoning_time_sec": gen_time}
        fout.write(json.dumps(out_rec) + "\n")
        fout.flush()
        reasoning_done[qid] = out_rec

for rec in retrieval_records_full:
    ans = reasoning_done.get(rec["question_id"])
    if ans:
        rec.update({"final_RoG_answer": ans["final_RoG_answer"], "reasoning_time_sec": ans["reasoning_time_sec"]})

with open(full_json_path, "w") as f:
    json.dump(retrieval_records_full, f, indent=2)
pd.DataFrame(retrieval_records_full).to_csv(full_csv_path, index=False)
print("Updated with final_RoG_answer and re-saved.")

Resuming: 1628 answers already generated.

Reasoning (full):   0%|          | 0/1628 [00:00<?, ?it/s]

Updated with final_RoG_answer and re-saved.

### Confirm the full reasoning loop

In [32]:
missing = [qid for qid in planning_by_id_full if qid not in reasoning_done]
print(f"{len(reasoning_done)} / {len(planning_by_id_full)} questions have a final answer.")
if missing:
    print(f"{len(missing)} still missing -- re-run the Cell 54 reasoning loop (it resumes automatically).")
else:
    print("Reasoning complete. Safe to proceed.")

1628 / 1628 questions have a final answer.
Reasoning complete. Safe to proceed.

### Memory Cache saved for reasoning

In [33]:
# === MEMORY: drop cached subgraphs now that WebQSP reasoning is done ===
import gc
for rec in planning_records_full:
    rec.pop("graph", None)
gc.collect()
print("Dropped cached subgraphs from planning_records_full to free RAM.")

Dropped cached subgraphs from planning_records_full to free RAM.

### Clean per-question table

In [34]:
from collections import defaultdict
import pandas as pd

retrieval_time_by_qid = defaultdict(float)
gold_reachable_by_qid = defaultdict(bool)
for rec in retrieval_records_full:
    retrieval_time_by_qid[rec["question_id"]] += rec["retrieval_time_sec"]
    gold_reachable_by_qid[rec["question_id"]] |= rec["gold_reachable"]

rows = []
for qid, prec in planning_by_id_full.items():
    rrow = reasoning_done.get(qid, {})
    rows.append({
        "id": qid,
        "question": prec["question"],
        "gold_answers": prec["a_entity"],
        "predicted_paths": prec["predicted_paths"],
        "planning_time_sec": prec["planning_time_sec"],
        "retrieval_time_sec": retrieval_time_by_qid.get(qid, 0.0),
        "reasoning_time_sec": rrow.get("reasoning_time_sec"),
        "final_RoG_answer": rrow.get("final_RoG_answer"),
        "gold_reachable": gold_reachable_by_qid.get(qid, False),
    })

per_question = pd.DataFrame(rows)
n = len(per_question)
assert per_question["reasoning_time_sec"].notna().all(), "Some questions missing reasoning -- finish Cell 54 first."
print(f"Per-question baseline table: {n} questions.")

Per-question baseline table: 1628 questions.

### Full per-question table

In [35]:
pd.set_option("display.max_colwidth", 100)  

display_cols = [
    "id", "question", "gold_answers", "predicted_paths",
    "planning_time_sec", "retrieval_time_sec", "reasoning_time_sec",
    "final_RoG_answer", "gold_reachable"
]

per_question_display = per_question[display_cols].rename(columns={"id": "question_id"})
per_question_display

,question_id,question,gold_answers,predicted_paths,planning_time_sec,retrieval_time_sec,reasoning_time_sec,final_RoG_answer,gold_reachable
0,WebQTest-0,what does jamaican people speak,"[Jamaican English, Jamaican Creole English Language]","[[location.country.languages_spoken], [language.human_language.countries_spoken_in], [location.c...",1.324136,0.003920,0.893439,Jamaican English\nJamaican Creole English Language,True
1,WebQTest-1,what did james k polk do before he was president,"[United States Representative, Governor of Tennessee, Speaker of the United States House of Repr...","[[government.government_position_held.office_holder, government.government_position_held.office_...",2.938305,0.000676,0.528926,United States Representative,True
2,WebQTest-3,who plays ken barlow in coronation street,[William Roache],"[[tv.tv_program.country_of_origin, people.person.nationality], [tv.regular_tv_appearance.series,...",1.790577,0.000319,0.472994,David Hanson,False
3,WebQTest-6,where is jamarcus russell from,[Mobile],"[[location.location.people_born_here], [people.person.place_of_birth], [people.person.nationality]]",1.032935,0.000264,0.461035,United States of America\nMobile,True
4,WebQTest-7,where was george washington carver from,[Diamond],"[[people.person.place_of_birth], [location.location.people_born_here], [people.person.nationality]]",1.034217,0.000151,0.583327,United States of America\nDiamond,True
...,...,...,...,...,...,...,...,...,...
1623,WebQTest-2027,what team did david beckham play for before la galaxy,[Manchester United F.C.],"[[sports.pro_athlete.teams, sports.sports_team_roster.team], [soccer.football_player.statistics,...",1.927255,0.000418,1.879107,Paris Saint-Germain F.C.\nA.C. Milan\nManchester United F.C.,True
1624,WebQTest-2028,who is the current leader of france 2010,[Nicolas Sarkozy],"[[people.person.nationality], [base.onephylogeny.type_of_thing.things_of_this_type, people.perso...",2.396295,0.003479,0.968816,Nicolas Sarkozy\nFrançois Hollande,True
1625,WebQTest-2029,where was the palace of knossos located,"[Crete, Greece]","[[location.location.containedby], [architecture.building.building_complex], [architecture.buildi...",0.821460,0.000087,0.154127,Greece,True
1626,WebQTest-2030,where is roswell area 51,"[Lincoln County, Nevada]","[[aviation.airport.serves], [location.location.containedby], [location.location.contains]]",0.892296,0.000057,0.214914,Lincoln County,True
1627,WebQTest-2031,when was father chris riley born,[Echuca],"[[people.person.place_of_birth], [people.person.place_of_birth, location.location.people_born_he...",1.704919,0.000047,0.386643,1951,False

### Saved as CSV and JSON

In [36]:
csv_out = os.path.join(FULL_OUTPUT_DIR, "webqsp_per_question_baseline.csv")
json_out = os.path.join(FULL_OUTPUT_DIR, "webqsp_per_question_baseline.json")

per_question_display.to_csv(csv_out, index=False)
per_question_display.to_json(json_out, orient="records", indent=2)

print("Saved:", csv_out)
print("Saved:", json_out)

Saved: /kaggle/working/step1_baseline_full/webqsp_per_question_baseline.csv
Saved: /kaggle/working/step1_baseline_full/webqsp_per_question_baseline.json

### Timing Statistics

In [37]:
def total_avg(col):
    total = per_question[col].sum()
    return total, total / n

plan_total, plan_avg = total_avg("planning_time_sec")
retr_total, retr_avg = total_avg("retrieval_time_sec")
reas_total, reas_avg = total_avg("reasoning_time_sec")
e2e_total = plan_total + retr_total + reas_total
e2e_avg = e2e_total / n

print(f"Total planning time:   {plan_total:9.1f} s  ({plan_total/60:7.2f} min)   avg/question: {plan_avg:.3f} s")
print(f"Total retrieval time:  {retr_total:9.1f} s  ({retr_total/60:7.2f} min)   avg/question: {retr_avg:.4f} s")
print(f"Total reasoning time:  {reas_total:9.1f} s  ({reas_total/60:7.2f} min)   avg/question: {reas_avg:.3f} s")
print(f"Total end-to-end time: {e2e_total:9.1f} s  ({e2e_total/60:7.2f} min)   avg/question: {e2e_avg:.3f} s")

Total planning time:      2634.3 s  (  43.91 min)   avg/question: 1.618 s
Total retrieval time:        1.2 s  (   0.02 min)   avg/question: 0.0008 s
Total reasoning time:     5148.2 s  (  85.80 min)   avg/question: 3.162 s
Total end-to-end time:    7783.7 s  ( 129.73 min)   avg/question: 4.781 s

### Retrieval Coverage and official Hit/Hits@1/F1

In [38]:
import sys
sys.path.append(os.path.join(REPO_DIR, "src"))
from qa_prediction.evaluate_results import eval_acc, eval_hit, eval_f1

n_covered = int(per_question["gold_reachable"].sum())
coverage_pct = 100 * n_covered / n

hit_list, acc_list, f1_list, prec_list, rec_list = [], [], [], [], []
for _, row in per_question.iterrows():
    prediction = [p for p in row["final_RoG_answer"].split("\n") if p.strip()]
    prediction_str = " ".join(prediction)
    f1, precision, recall = eval_f1(prediction, row["gold_answers"])
    hit_list.append(eval_hit(prediction_str, row["gold_answers"]))
    acc_list.append(eval_acc(prediction_str, row["gold_answers"]))
    f1_list.append(f1); prec_list.append(precision); rec_list.append(recall)

hits1_pct = 100 * sum(hit_list) / n
f1_pct = 100 * sum(f1_list) / n

print(f"Questions reaching >=1 gold: {n_covered}")
print(f"Question-level retrieval coverage: {coverage_pct:.2f}%")
print(f"Hit/Hits@1: {hits1_pct:.2f}%")
print(f"F1: {f1_pct:.2f}%")

Questions reaching >=1 gold: 1369
Question-level retrieval coverage: 84.09%
Hit/Hits@1: 85.93%
F1: 70.27%

### Freezing Baseline

In [39]:
baseline_summary = f"""Dataset: WebQSP
Test questions: {n}

Retrieval:
  Questions reaching >=1 gold: {n_covered}
  Question-level retrieval coverage: {coverage_pct:.2f}%

Timing:
  Total planning time:   {plan_total:.1f} s ({plan_total/60:.2f} min)   Avg/question: {plan_avg:.3f} s
  Total retrieval time:  {retr_total:.1f} s ({retr_total/60:.2f} min)   Avg/question: {retr_avg:.4f} s
  Total reasoning time:  {reas_total:.1f} s ({reas_total/60:.2f} min)   Avg/question: {reas_avg:.3f} s
  Total end-to-end time: {e2e_total:.1f} s ({e2e_total/60:.2f} min)   Avg/question: {e2e_avg:.3f} s

Final QA:
  Hit/Hits@1: {hits1_pct:.2f}%
  F1: {f1_pct:.2f}%
"""
print(baseline_summary)

with open(os.path.join(FULL_OUTPUT_DIR, "webqsp_baseline_summary.txt"), "w") as f:
    f.write(baseline_summary)

per_question.to_json(os.path.join(FULL_OUTPUT_DIR, "webqsp_baseline_predictions.json"), orient="records", indent=2)
per_question.to_csv(os.path.join(FULL_OUTPUT_DIR, "webqsp_baseline_predictions.csv"), index=False)
print("Baseline frozen.")

Dataset: WebQSP
Test questions: 1628

Retrieval:
  Questions reaching >=1 gold: 1369
  Question-level retrieval coverage: 84.09%

Timing:
  Total planning time:   2634.3 s (43.91 min)   Avg/question: 1.618 s
  Total retrieval time:  1.2 s (0.02 min)   Avg/question: 0.0008 s
  Total reasoning time:  5148.2 s (85.80 min)   Avg/question: 3.162 s
  Total end-to-end time: 7783.7 s (129.73 min)   Avg/question: 4.781 s

Final QA:
  Hit/Hits@1: 85.93%
  F1: 70.27%

Baseline frozen.

### Memory clear of RoG-WebQSP

In [40]:
# === MEMORY: clear WebQSP intermediates before starting CWQ ===
import torch
for _name in ["retrieval_records_full", "retrieval_records", "planning_records",
              "df_full", "df_pilot", "default_decode_records"]:
    if _name in globals():
        del globals()[_name]
gc.collect()
torch.cuda.empty_cache()
print("GPU memory reserved:", f"{torch.cuda.memory_reserved()/1e9:.2f} GB")

GPU memory reserved: 6.92 GB

### LeBron James Triple Retrieval

In [41]:
import json
from collections import defaultdict
from utils.graph_utils import build_graph

target_qid = "WebQTest-268"
rec = None
with open(PLANNING_CKPT) as f:
    for line in f:
        r = json.loads(line)
        if r["id"] == target_qid:
            rec = r
            break

G = build_graph(rec["graph"])
topic = rec["q_entity"][0]  # "LeBron James"

# Group every real 1-hop edge (in either direction) touching the topic entity,
# by relation type -- this is your pool of "Batman / Alfred / Chris Nolan"-style
# context facts for a richer illustrative figure.
outgoing = defaultdict(list)
for nbr in G.neighbors(topic):
    rel = G[topic][nbr]["relation"]
    outgoing[rel].append(nbr)

incoming = defaultdict(list)
for src in G.nodes():
    if src == topic:
        continue
    if G.has_edge(src, topic):
        rel = G[src][topic]["relation"]
        incoming[rel].append(src)

print(f"=== Outgoing relations from '{topic}' ({len(outgoing)} distinct relations) ===")
for rel, targets in sorted(outgoing.items(), key=lambda kv: -len(kv[1])):
    sample = targets[:5]
    print(f"  [{len(targets):>3}x] {rel}  ->  {sample}{' ...' if len(targets) > 5 else ''}")

print(f"\n=== Incoming relations to '{topic}' ({len(incoming)} distinct relations) ===")
for rel, sources in sorted(incoming.items(), key=lambda kv: -len(kv[1])):
    sample = sources[:5]
    print(f"  [{len(sources):>3}x] {rel}  <-  {sample}{' ...' if len(sources) > 5 else ''}")


target_qid = "WebQTest-268"
rec = None
with open(PLANNING_CKPT) as f:
    for line in f:
        r = json.loads(line)
        if r["id"] == target_qid:
            rec = r
            break

G = build_graph(rec["graph"])
topic = rec["q_entity"][0]  # "LeBron James"

# Group every real 1-hop edge (in either direction) touching the topic entity,
# by relation type -- this is your pool of "Batman / Alfred / Chris Nolan"-style
# context facts for a richer illustrative figure.
outgoing = defaultdict(list)
for nbr in G.neighbors(topic):
    rel = G[topic][nbr]["relation"]
    outgoing[rel].append(nbr)

incoming = defaultdict(list)
for src in G.nodes():
    if src == topic:
        continue
    if G.has_edge(src, topic):
        rel = G[src][topic]["relation"]
        incoming[rel].append(src)

print(f"=== Outgoing relations from '{topic}' ({len(outgoing)} distinct relations) ===")
for rel, targets in sorted(outgoing.items(), key=lambda kv: -len(kv[1])):
    sample = targets[:5]
    print(f"  [{len(targets):>3}x] {rel}  ->  {sample}{' ...' if len(targets) > 5 else ''}")

print(f"\n=== Incoming relations to '{topic}' ({len(incoming)} distinct relations) ===")
for rel, sources in sorted(incoming.items(), key=lambda kv: -len(kv[1])):
    sample = sources[:5]
    print(f"  [{len(sources):>3}x] {rel}  <-  {sample}{' ...' if len(sources) > 5 else ''}")

=== Outgoing relations from 'LeBron James' (64 distinct relations) ===
  [ 26x] award.award_winner.awards_won  ->  ['m.0_qrm17', 'm.0yg0zky', 'm.0z66wqh', 'm.0_qrd1p', 'm.0_qrgh9'] ...
  [ 23x] award.award_nominee.award_nominations  ->  ['m.0sgkpd0', 'm.0z1p_l5', 'm.0z9ljvh', 'm.0z5blfv', 'm.0y_yc47'] ...
  [ 20x] award.award_nomination.award_nominee  ->  ['m.0z1n6dn', 'm.0_spmjw', 'm.010w6vqp', 'm.0z43z7_', 'm.0z3v44c'] ...
  [ 16x] award.award_honor.award_winner  ->  ['m.0_qvzz1', 'm.0_qr864', 'm.0x0zlfg', 'm.0_qrlpv', 'm.0x0z10c'] ...
  [ 13x] film.personal_film_appearance.person  ->  ['m.0v4mj0y', 'm.0v4ndsn', 'm.0v4mlsf', 'm.0v462vn', 'm.0v4mk_2'] ...
  [  9x] tv.tv_guest_role.actor  ->  ['m.0y7ls9m', 'm.0y7htk3', 'm.0kb00b3', 'm.0y7j8ry', 'm.0y7klbl'] ...
  [  9x] freebase.valuenotation.is_reviewed  ->  ['Parents', 'Date of birth', 'Children', 'Place of birth', 'Weight'] ...
  [  8x] common.topic.webpage  ->  ['m.0kg5v20', 'm.0bnsx2n', 'm.09wlf17', 'm.09ymk3w', 'm.09x22v7'] ...
  [  8x] film.person_or_entity_appearing_in_film.films  ->  ['m.0v4n9vx', 'm.0v4ncmr', 'm.0v464nl', 'm.0y7lnys', 'm.0107blsl'] ...
  [  5x] basketball.basketball_player_stats.player  ->  ['m.04qmm8m', 'm.04qcjh2', 'm.04qmsr4', 'm.04qp97c', 'm.04ql_x2']
  [  5x] people.person.profession  ->  ['Voice Actor', 'Basketball player', 'Television producer', 'Screenwriter', 'Athlete']
  [  4x] common.topic.image  ->  ['Lebron James', 'LeBron James 2', 'lebron-james.jpg', 'LeBron James']
  [  4x] common.webpage.topic  ->  ['m.09yjt3y', 'm.09yh16v', 'm.0b47jzs', 'm.0cvmhlb']
  [  4x] sports.sports_award_winner.awards  ->  ['m.04ynxp7', 'm.02kbccr', 'm.062txq3', 'm.0k0545f']
  [  3x] tv.tv_actor.guest_roles  ->  ['m.0y7k84w', 'm.09nb79p', 'm.0y7hr3h']
  [  3x] tv.tv_episode_segment.personal_appearances  ->  ['m.0khq_s7', 'm.0khq_qd', 'm.0kkj72n']
  [  3x] sports.sports_award.award_winner  ->  ['m.0k0543c', 'm.0w0h79l', 'm.04ynxph']
  [  3x] common.topic.notable_types  ->  ['TV Episode', 'Basketball Player', 'Book']
  [  3x] olympics.olympic_athlete.country  ->  ['m.0k8rqy4', 'm.04f9f2d', 'm.04fl3fv']
  [  3x] people.person.places_lived  ->  ['m.03pfl7k', 'm.0kfxz0z', 'm.03pr62x']
  [  3x] people.person.children  ->  ['LeBron James Jr.', 'Bryce Maximus James', 'Anthony McClelland']
  [  3x] sports.pro_athlete.teams  ->  ['m.011461z_', 'm.012z6mb1', 'm.0csn6xn']
  [  2x] tv.tv_personality.tv_regular_appearances  ->  ['m.0v45r6d', 'm.0ybfjfs']
  [  2x] tv.tv_segment_personal_appearance.person  ->  ['m.0khq_nf', 'm.0kjl_p5']
  [  2x] tv.tv_producer.tv_episodes_produced  ->  ['m.011x2jxp', 'm.011x2qqn']
  [  2x] base.schemastaging.athlete_salary.athlete  ->  ['m.0j_8xt1', 'm.0_r6zcj']
  [  2x] tv.tv_producer.programs_produced  ->  ['m.0t_92_c', 'm.011x17zz']
  [  2x] base.schemastaging.athlete_extra.salary  ->  ['m.0plswgw', 'm.0j2x60b']
  [  2x] music.recording.artist  ->  ['Intro', 'Outro']
  [  2x] sports.sports_team_roster.player  ->  ['m.02398d8', 'm.0z7hgc_']
  [  2x] basketball.basketball_player.position_s  ->  ['Small forward', 'Power forward']
  [  2x] book.written_work.author  ->  ['Shooting Stars', 'Lew Freedman']
  [  2x] common.topic.notable_for  ->  ['g.1256y2gpm', 'g.125509zk3']
  [  1x] business.sponsorship.sponsored_recipient  ->  ['m.03n9_n7']
  [  1x] basketball.basketball_position.players  ->  ['Point forward']
  [  1x] people.person.ethnicity  ->  ['African American']
  [  1x] people.person.spouse_s  ->  ['m.0y8c6k2']
  [  1x] tv.tv_segment_personal_appearance.segment  ->  ['m.0kfggqh']
  [  1x] tv.tv_actor.starring_roles  ->  ['m.0t_92x5']
  [  1x] base.popstra.celebrity.infidelity_participant  ->  ['m.063y076']
  [  1x] people.group_membership.member  ->  ['m.01146ms7']
  [  1x] tv.tv_writer.tv_programs  ->  ['m.0t_92_0']
  [  1x] people.marriage.spouse  ->  ['m.04g4z6t']
  [  1x] base.popstra.celebrity.friendship  ->  ['m.0h4xsfb']
  [  1x] sports.pro_sports_played.athlete  ->  ['m.0c3p_f6']
  [  1x] olympics.olympic_medal_honor.medalist  ->  ['m.0krvwc7']
  [  1x] basketball.basketball_player_career_stats.player  ->  ['m.04g4zm0']
  [  1x] common.image.size  ->  ['m.02f01qx']
  [  1x] book.written_work.subjects  ->  ['Meet Lebron James']
  [  1x] olympics.olympic_athlete.medals_won  ->  ['m.04fl3dr']
  [  1x] tv.tv_regular_personal_appearance.person  ->  ['m.0kfqxgn']
  [  1x] people.person.place_of_birth  ->  ['Akron']
  [  1x] tv.tv_program_guest.appeared_on  ->  ['m.0kfb_jk']
  [  1x] sports.sports_league_draft_pick.player  ->  ['m.04fl3dj']
  [  1x] people.person.parents  ->  ['Gloria Marie James']
  [  1x] film.film.executive_produced_by  ->  ['More than a Game']
  [  1x] education.education.student  ->  ['m.040qhv9']
  [  1x] base.saturdaynightlive.snl_host.episodes_hosted  ->  ['LeBron James/Kanye West']
  [  1x] people.person.nationality  ->  ['United States of America']
  [  1x] common.topic.article  ->  ['m.01jz6q']
  [  1x] freebase.valuenotation.has_no_value  ->  ['Siblings']
  [  1x] people.person.gender  ->  ['Male']
  [  1x] film.actor.film  ->  ['g.11bbrhyr4z']
  [  1x] base.schemastaging.person_extra.net_worth  ->  ['m.0j2x62m']

=== Incoming relations to 'LeBron James' (64 distinct relations) ===
  [ 26x] award.award_winner.awards_won  <-  ['m.0x0wvvk', 'm.0_qr6bw', 'm.0x0ww2n', 'm.0_qrm17', 'm.0yg0zky'] ...
  [ 23x] award.award_nominee.award_nominations  <-  ['m.0z7yzvr', 'm.0sgkpd0', 'm.0z5blfv', 'm.0sgl513', 'm.0z3sxnh'] ...
  [ 20x] award.award_nomination.award_nominee  <-  ['m.0z1n6dn', 'm.0_spmjw', 'm.0z3v44c', 'm.0115gb6f', 'm.010_xz3j'] ...
  [ 16x] award.award_honor.award_winner  <-  ['m.0_qr864', 'm.0_qvzz1', 'm.0yg0y_2', 'm.0_qtsk9', 'm.0yg0_0r'] ...
  [ 13x] film.personal_film_appearance.person  <-  ['m.0v4ndsn', 'm.0v4663b', 'm.0v4nckg', 'm.0v4mkf7', 'm.0v4mj0y'] ...
  [  9x] freebase.valuenotation.is_reviewed  <-  ['Date of birth', 'Gender', 'Country of nationality', 'Children', 'Parents'] ...
  [  9x] tv.tv_guest_role.actor  <-  ['m.0y7ls9m', 'm.0y7htk3', 'm.0kb00b3', 'm.0y7j8ry', 'm.0y7klbl'] ...
  [  8x] common.topic.webpage  <-  ['m.0kg5v20', 'm.0bnsx2n', 'm.09wlf17', 'm.09ymk3w', 'm.0b48_yp'] ...
  [  8x] film.person_or_entity_appearing_in_film.films  <-  ['m.0107blsl', 'm.0pc9rsr', 'm.0v4n9vx', 'm.0v4mp1x', 'm.0v4ncmr'] ...
  [  5x] people.person.profession  <-  ['Voice Actor', 'Basketball player', 'Athlete', 'Screenwriter', 'Television producer']
  [  5x] basketball.basketball_player_stats.player  <-  ['m.04qmm8m', 'm.04qcjh2', 'm.04qp97c', 'm.04qmsr4', 'm.04ql_x2']
  [  4x] common.webpage.topic  <-  ['m.09yjt3y', 'm.09yh16v', 'm.0b47jzs', 'm.0cvmhlb']
  [  4x] sports.sports_award_winner.awards  <-  ['m.04ynxp7', 'm.02kbccr', 'm.062txq3', 'm.0k0545f']
  [  3x] common.topic.notable_types  <-  ['Basketball Player', 'TV Episode', 'Book']
  [  3x] common.topic.image  <-  ['Lebron James', 'LeBron James 2', 'lebron-james.jpg']
  [  3x] tv.tv_actor.guest_roles  <-  ['m.0y7k84w', 'm.09nb79p', 'm.0y7hr3h']
  [  3x] sports.sports_award.award_winner  <-  ['m.04ynxph', 'm.0k0543c', 'm.0w0h79l']
  [  3x] tv.tv_episode_segment.personal_appearances  <-  ['m.0khq_s7', 'm.0khq_qd', 'm.0kkj72n']
  [  3x] olympics.olympic_athlete.country  <-  ['m.0k8rqy4', 'm.04f9f2d', 'm.04fl3fv']
  [  3x] people.person.places_lived  <-  ['m.03pfl7k', 'm.0kfxz0z', 'm.03pr62x']
  [  3x] people.person.children  <-  ['LeBron James Jr.', 'Anthony McClelland', 'Bryce Maximus James']
  [  3x] sports.pro_athlete.teams  <-  ['m.0csn6xn', 'm.012z6mb1', 'm.011461z_']
  [  2x] base.schemastaging.athlete_extra.salary  <-  ['m.0plswgw', 'm.0j2x60b']
  [  2x] tv.tv_personality.tv_regular_appearances  <-  ['m.0v45r6d', 'm.0ybfjfs']
  [  2x] tv.tv_segment_personal_appearance.person  <-  ['m.0khq_nf', 'm.0kjl_p5']
  [  2x] tv.tv_producer.tv_episodes_produced  <-  ['m.011x2qqn', 'm.011x2jxp']
  [  2x] basketball.basketball_player.position_s  <-  ['Small forward', 'Power forward']
  [  2x] sports.sports_team_roster.player  <-  ['m.02398d8', 'm.0z7hgc_']
  [  2x] base.schemastaging.athlete_salary.athlete  <-  ['m.0_r6zcj', 'm.0j_8xt1']
  [  2x] book.written_work.author  <-  ['Shooting Stars', 'Lew Freedman']
  [  2x] tv.tv_producer.programs_produced  <-  ['m.0t_92_c', 'm.011x17zz']
  [  2x] music.recording.artist  <-  ['Intro', 'Outro']
  [  2x] common.topic.notable_for  <-  ['g.1256y2gpm', 'g.125509zk3']
  [  1x] film.film.executive_produced_by  <-  ['More than a Game']
  [  1x] people.person.ethnicity  <-  ['African American']
  [  1x] sports.sports_league_draft_pick.player  <-  ['m.04fl3dj']
  [  1x] base.schemastaging.person_extra.net_worth  <-  ['m.0j2x62m']
  [  1x] people.person.spouse_s  <-  ['m.0y8c6k2']
  [  1x] basketball.basketball_position.players  <-  ['Point forward']
  [  1x] olympics.olympic_athlete.medals_won  <-  ['m.04fl3dr']
  [  1x] business.sponsorship.sponsored_recipient  <-  ['m.03n9_n7']
  [  1x] people.person.nationality  <-  ['United States of America']
  [  1x] olympics.olympic_medal_honor.medalist  <-  ['m.0krvwc7']
  [  1x] freebase.valuenotation.has_no_value  <-  ['Siblings']
  [  1x] tv.tv_actor.starring_roles  <-  ['m.0t_92x5']
  [  1x] people.marriage.spouse  <-  ['m.04g4z6t']
  [  1x] people.person.gender  <-  ['Male']
  [  1x] base.saturdaynightlive.snl_host.episodes_hosted  <-  ['LeBron James/Kanye West']
  [  1x] people.group_membership.member  <-  ['m.01146ms7']
  [  1x] sports.pro_sports_played.athlete  <-  ['m.0c3p_f6']
  [  1x] tv.tv_segment_personal_appearance.segment  <-  ['m.0kfggqh']
  [  1x] people.person.place_of_birth  <-  ['Akron']
  [  1x] people.person.parents  <-  ['Gloria Marie James']
  [  1x] base.popstra.celebrity.infidelity_participant  <-  ['m.063y076']
  [  1x] tv.tv_writer.tv_programs  <-  ['m.0t_92_0']
  [  1x] tv.tv_regular_personal_appearance.person  <-  ['m.0kfqxgn']
  [  1x] base.popstra.celebrity.friendship  <-  ['m.0h4xsfb']
  [  1x] basketball.basketball_player_career_stats.player  <-  ['m.04g4zm0']
  [  1x] common.image.size  <-  ['m.02f01qx']
  [  1x] book.written_work.subjects  <-  ['Meet Lebron James']
  [  1x] education.education.student  <-  ['m.040qhv9']
  [  1x] tv.tv_program_guest.appeared_on  <-  ['m.0kfb_jk']
  [  1x] common.topic.article  <-  ['m.01jz6q']
  [  1x] film.actor.film  <-  ['g.11bbrhyr4z']
=== Outgoing relations from 'LeBron James' (64 distinct relations) ===
  [ 26x] award.award_winner.awards_won  ->  ['m.0_qrm17', 'm.0yg0zky', 'm.0z66wqh', 'm.0_qrd1p', 'm.0_qrgh9'] ...
  [ 23x] award.award_nominee.award_nominations  ->  ['m.0sgkpd0', 'm.0z1p_l5', 'm.0z9ljvh', 'm.0z5blfv', 'm.0y_yc47'] ...
  [ 20x] award.award_nomination.award_nominee  ->  ['m.0z1n6dn', 'm.0_spmjw', 'm.010w6vqp', 'm.0z43z7_', 'm.0z3v44c'] ...
  [ 16x] award.award_honor.award_winner  ->  ['m.0_qvzz1', 'm.0_qr864', 'm.0x0zlfg', 'm.0_qrlpv', 'm.0x0z10c'] ...
  [ 13x] film.personal_film_appearance.person  ->  ['m.0v4mj0y', 'm.0v4ndsn', 'm.0v4mlsf', 'm.0v462vn', 'm.0v4mk_2'] ...
  [  9x] tv.tv_guest_role.actor  ->  ['m.0y7ls9m', 'm.0y7htk3', 'm.0kb00b3', 'm.0y7j8ry', 'm.0y7klbl'] ...
  [  9x] freebase.valuenotation.is_reviewed  ->  ['Parents', 'Date of birth', 'Children', 'Place of birth', 'Weight'] ...
  [  8x] common.topic.webpage  ->  ['m.0kg5v20', 'm.0bnsx2n', 'm.09wlf17', 'm.09ymk3w', 'm.09x22v7'] ...
  [  8x] film.person_or_entity_appearing_in_film.films  ->  ['m.0v4n9vx', 'm.0v4ncmr', 'm.0v464nl', 'm.0y7lnys', 'm.0107blsl'] ...
  [  5x] basketball.basketball_player_stats.player  ->  ['m.04qmm8m', 'm.04qcjh2', 'm.04qmsr4', 'm.04qp97c', 'm.04ql_x2']
  [  5x] people.person.profession  ->  ['Voice Actor', 'Basketball player', 'Television producer', 'Screenwriter', 'Athlete']
  [  4x] common.topic.image  ->  ['Lebron James', 'LeBron James 2', 'lebron-james.jpg', 'LeBron James']
  [  4x] common.webpage.topic  ->  ['m.09yjt3y', 'm.09yh16v', 'm.0b47jzs', 'm.0cvmhlb']
  [  4x] sports.sports_award_winner.awards  ->  ['m.04ynxp7', 'm.02kbccr', 'm.062txq3', 'm.0k0545f']
  [  3x] tv.tv_actor.guest_roles  ->  ['m.0y7k84w', 'm.09nb79p', 'm.0y7hr3h']
  [  3x] tv.tv_episode_segment.personal_appearances  ->  ['m.0khq_s7', 'm.0khq_qd', 'm.0kkj72n']
  [  3x] sports.sports_award.award_winner  ->  ['m.0k0543c', 'm.0w0h79l', 'm.04ynxph']
  [  3x] common.topic.notable_types  ->  ['TV Episode', 'Basketball Player', 'Book']
  [  3x] olympics.olympic_athlete.country  ->  ['m.0k8rqy4', 'm.04f9f2d', 'm.04fl3fv']
  [  3x] people.person.places_lived  ->  ['m.03pfl7k', 'm.0kfxz0z', 'm.03pr62x']
  [  3x] people.person.children  ->  ['LeBron James Jr.', 'Bryce Maximus James', 'Anthony McClelland']
  [  3x] sports.pro_athlete.teams  ->  ['m.011461z_', 'm.012z6mb1', 'm.0csn6xn']
  [  2x] tv.tv_personality.tv_regular_appearances  ->  ['m.0v45r6d', 'm.0ybfjfs']
  [  2x] tv.tv_segment_personal_appearance.person  ->  ['m.0khq_nf', 'm.0kjl_p5']
  [  2x] tv.tv_producer.tv_episodes_produced  ->  ['m.011x2jxp', 'm.011x2qqn']
  [  2x] base.schemastaging.athlete_salary.athlete  ->  ['m.0j_8xt1', 'm.0_r6zcj']
  [  2x] tv.tv_producer.programs_produced  ->  ['m.0t_92_c', 'm.011x17zz']
  [  2x] base.schemastaging.athlete_extra.salary  ->  ['m.0plswgw', 'm.0j2x60b']
  [  2x] music.recording.artist  ->  ['Intro', 'Outro']
  [  2x] sports.sports_team_roster.player  ->  ['m.02398d8', 'm.0z7hgc_']
  [  2x] basketball.basketball_player.position_s  ->  ['Small forward', 'Power forward']
  [  2x] book.written_work.author  ->  ['Shooting Stars', 'Lew Freedman']
  [  2x] common.topic.notable_for  ->  ['g.1256y2gpm', 'g.125509zk3']
  [  1x] business.sponsorship.sponsored_recipient  ->  ['m.03n9_n7']
  [  1x] basketball.basketball_position.players  ->  ['Point forward']
  [  1x] people.person.ethnicity  ->  ['African American']
  [  1x] people.person.spouse_s  ->  ['m.0y8c6k2']
  [  1x] tv.tv_segment_personal_appearance.segment  ->  ['m.0kfggqh']
  [  1x] tv.tv_actor.starring_roles  ->  ['m.0t_92x5']
  [  1x] base.popstra.celebrity.infidelity_participant  ->  ['m.063y076']
  [  1x] people.group_membership.member  ->  ['m.01146ms7']
  [  1x] tv.tv_writer.tv_programs  ->  ['m.0t_92_0']
  [  1x] people.marriage.spouse  ->  ['m.04g4z6t']
  [  1x] base.popstra.celebrity.friendship  ->  ['m.0h4xsfb']
  [  1x] sports.pro_sports_played.athlete  ->  ['m.0c3p_f6']
  [  1x] olympics.olympic_medal_honor.medalist  ->  ['m.0krvwc7']
  [  1x] basketball.basketball_player_career_stats.player  ->  ['m.04g4zm0']
  [  1x] common.image.size  ->  ['m.02f01qx']
  [  1x] book.written_work.subjects  ->  ['Meet Lebron James']
  [  1x] olympics.olympic_athlete.medals_won  ->  ['m.04fl3dr']
  [  1x] tv.tv_regular_personal_appearance.person  ->  ['m.0kfqxgn']
  [  1x] people.person.place_of_birth  ->  ['Akron']
  [  1x] tv.tv_program_guest.appeared_on  ->  ['m.0kfb_jk']
  [  1x] sports.sports_league_draft_pick.player  ->  ['m.04fl3dj']
  [  1x] people.person.parents  ->  ['Gloria Marie James']
  [  1x] film.film.executive_produced_by  ->  ['More than a Game']
  [  1x] education.education.student  ->  ['m.040qhv9']
  [  1x] base.saturdaynightlive.snl_host.episodes_hosted  ->  ['LeBron James/Kanye West']
  [  1x] people.person.nationality  ->  ['United States of America']
  [  1x] common.topic.article  ->  ['m.01jz6q']
  [  1x] freebase.valuenotation.has_no_value  ->  ['Siblings']
  [  1x] people.person.gender  ->  ['Male']
  [  1x] film.actor.film  ->  ['g.11bbrhyr4z']
  [  1x] base.schemastaging.person_extra.net_worth  ->  ['m.0j2x62m']

=== Incoming relations to 'LeBron James' (64 distinct relations) ===
  [ 26x] award.award_winner.awards_won  <-  ['m.0x0wvvk', 'm.0_qr6bw', 'm.0x0ww2n', 'm.0_qrm17', 'm.0yg0zky'] ...
  [ 23x] award.award_nominee.award_nominations  <-  ['m.0z7yzvr', 'm.0sgkpd0', 'm.0z5blfv', 'm.0sgl513', 'm.0z3sxnh'] ...
  [ 20x] award.award_nomination.award_nominee  <-  ['m.0z1n6dn', 'm.0_spmjw', 'm.0z3v44c', 'm.0115gb6f', 'm.010_xz3j'] ...
  [ 16x] award.award_honor.award_winner  <-  ['m.0_qr864', 'm.0_qvzz1', 'm.0yg0y_2', 'm.0_qtsk9', 'm.0yg0_0r'] ...
  [ 13x] film.personal_film_appearance.person  <-  ['m.0v4ndsn', 'm.0v4663b', 'm.0v4nckg', 'm.0v4mkf7', 'm.0v4mj0y'] ...
  [  9x] freebase.valuenotation.is_reviewed  <-  ['Date of birth', 'Gender', 'Country of nationality', 'Children', 'Parents'] ...
  [  9x] tv.tv_guest_role.actor  <-  ['m.0y7ls9m', 'm.0y7htk3', 'm.0kb00b3', 'm.0y7j8ry', 'm.0y7klbl'] ...
  [  8x] common.topic.webpage  <-  ['m.0kg5v20', 'm.0bnsx2n', 'm.09wlf17', 'm.09ymk3w', 'm.0b48_yp'] ...
  [  8x] film.person_or_entity_appearing_in_film.films  <-  ['m.0107blsl', 'm.0pc9rsr', 'm.0v4n9vx', 'm.0v4mp1x', 'm.0v4ncmr'] ...
  [  5x] people.person.profession  <-  ['Voice Actor', 'Basketball player', 'Athlete', 'Screenwriter', 'Television producer']
  [  5x] basketball.basketball_player_stats.player  <-  ['m.04qmm8m', 'm.04qcjh2', 'm.04qp97c', 'm.04qmsr4', 'm.04ql_x2']
  [  4x] common.webpage.topic  <-  ['m.09yjt3y', 'm.09yh16v', 'm.0b47jzs', 'm.0cvmhlb']
  [  4x] sports.sports_award_winner.awards  <-  ['m.04ynxp7', 'm.02kbccr', 'm.062txq3', 'm.0k0545f']
  [  3x] common.topic.notable_types  <-  ['Basketball Player', 'TV Episode', 'Book']
  [  3x] common.topic.image  <-  ['Lebron James', 'LeBron James 2', 'lebron-james.jpg']
  [  3x] tv.tv_actor.guest_roles  <-  ['m.0y7k84w', 'm.09nb79p', 'm.0y7hr3h']
  [  3x] sports.sports_award.award_winner  <-  ['m.04ynxph', 'm.0k0543c', 'm.0w0h79l']
  [  3x] tv.tv_episode_segment.personal_appearances  <-  ['m.0khq_s7', 'm.0khq_qd', 'm.0kkj72n']
  [  3x] olympics.olympic_athlete.country  <-  ['m.0k8rqy4', 'm.04f9f2d', 'm.04fl3fv']
  [  3x] people.person.places_lived  <-  ['m.03pfl7k', 'm.0kfxz0z', 'm.03pr62x']
  [  3x] people.person.children  <-  ['LeBron James Jr.', 'Anthony McClelland', 'Bryce Maximus James']
  [  3x] sports.pro_athlete.teams  <-  ['m.0csn6xn', 'm.012z6mb1', 'm.011461z_']
  [  2x] base.schemastaging.athlete_extra.salary  <-  ['m.0plswgw', 'm.0j2x60b']
  [  2x] tv.tv_personality.tv_regular_appearances  <-  ['m.0v45r6d', 'm.0ybfjfs']
  [  2x] tv.tv_segment_personal_appearance.person  <-  ['m.0khq_nf', 'm.0kjl_p5']
  [  2x] tv.tv_producer.tv_episodes_produced  <-  ['m.011x2qqn', 'm.011x2jxp']
  [  2x] basketball.basketball_player.position_s  <-  ['Small forward', 'Power forward']
  [  2x] sports.sports_team_roster.player  <-  ['m.02398d8', 'm.0z7hgc_']
  [  2x] base.schemastaging.athlete_salary.athlete  <-  ['m.0_r6zcj', 'm.0j_8xt1']
  [  2x] book.written_work.author  <-  ['Shooting Stars', 'Lew Freedman']
  [  2x] tv.tv_producer.programs_produced  <-  ['m.0t_92_c', 'm.011x17zz']
  [  2x] music.recording.artist  <-  ['Intro', 'Outro']
  [  2x] common.topic.notable_for  <-  ['g.1256y2gpm', 'g.125509zk3']
  [  1x] film.film.executive_produced_by  <-  ['More than a Game']
  [  1x] people.person.ethnicity  <-  ['African American']
  [  1x] sports.sports_league_draft_pick.player  <-  ['m.04fl3dj']
  [  1x] base.schemastaging.person_extra.net_worth  <-  ['m.0j2x62m']
  [  1x] people.person.spouse_s  <-  ['m.0y8c6k2']
  [  1x] basketball.basketball_position.players  <-  ['Point forward']
  [  1x] olympics.olympic_athlete.medals_won  <-  ['m.04fl3dr']
  [  1x] business.sponsorship.sponsored_recipient  <-  ['m.03n9_n7']
  [  1x] people.person.nationality  <-  ['United States of America']
  [  1x] olympics.olympic_medal_honor.medalist  <-  ['m.0krvwc7']
  [  1x] freebase.valuenotation.has_no_value  <-  ['Siblings']
  [  1x] tv.tv_actor.starring_roles  <-  ['m.0t_92x5']
  [  1x] people.marriage.spouse  <-  ['m.04g4z6t']
  [  1x] people.person.gender  <-  ['Male']
  [  1x] base.saturdaynightlive.snl_host.episodes_hosted  <-  ['LeBron James/Kanye West']
  [  1x] people.group_membership.member  <-  ['m.01146ms7']
  [  1x] sports.pro_sports_played.athlete  <-  ['m.0c3p_f6']
  [  1x] tv.tv_segment_personal_appearance.segment  <-  ['m.0kfggqh']
  [  1x] people.person.place_of_birth  <-  ['Akron']
  [  1x] people.person.parents  <-  ['Gloria Marie James']
  [  1x] base.popstra.celebrity.infidelity_participant  <-  ['m.063y076']
  [  1x] tv.tv_writer.tv_programs  <-  ['m.0t_92_0']

In [42]:
import json
from collections import defaultdict
from utils.graph_utils import build_graph

target_qid = "WebQTest-268"
rec = None
with open(PLANNING_CKPT) as f:
    for line in f:
        r = json.loads(line)
        if r["id"] == target_qid:
            rec = r
            break

G = build_graph(rec["graph"])
topic = rec["q_entity"][0]  # "LeBron James"

# Group every real 1-hop edge (in either direction) touching the topic entity,
# by relation type -- this is your pool of "Batman / Alfred / Chris Nolan"-style
# context facts for a richer illustrative figure.
outgoing = defaultdict(list)
for nbr in G.neighbors(topic):
    rel = G[topic][nbr]["relation"]
    outgoing[rel].append(nbr)

incoming = defaultdict(list)
for src in G.nodes():
    if src == topic:
        continue
    if G.has_edge(src, topic):
        rel = G[src][topic]["relation"]
        incoming[rel].append(src)

print(f"=== Outgoing relations from '{topic}' ({len(outgoing)} distinct relations) ===")
for rel, targets in sorted(outgoing.items(), key=lambda kv: -len(kv[1])):
    sample = targets[:5]
    print(f"  [{len(targets):>3}x] {rel}  ->  {sample}{' ...' if len(targets) > 5 else ''}")

print(f"\n=== Incoming relations to '{topic}' ({len(incoming)} distinct relations) ===")
for rel, sources in sorted(incoming.items(), key=lambda kv: -len(kv[1])):
    sample = sources[:5]
    print(f"  [{len(sources):>3}x] {rel}  <-  {sample}{' ...' if len(sources) > 5 else ''}")

=== Outgoing relations from 'LeBron James' (64 distinct relations) ===
  [ 26x] award.award_winner.awards_won  ->  ['m.0_qrm17', 'm.0yg0zky', 'm.0z66wqh', 'm.0_qrd1p', 'm.0_qrgh9'] ...
  [ 23x] award.award_nominee.award_nominations  ->  ['m.0sgkpd0', 'm.0z1p_l5', 'm.0z9ljvh', 'm.0z5blfv', 'm.0y_yc47'] ...
  [ 20x] award.award_nomination.award_nominee  ->  ['m.0z1n6dn', 'm.0_spmjw', 'm.010w6vqp', 'm.0z43z7_', 'm.0z3v44c'] ...
  [ 16x] award.award_honor.award_winner  ->  ['m.0_qvzz1', 'm.0_qr864', 'm.0x0zlfg', 'm.0_qrlpv', 'm.0x0z10c'] ...
  [ 13x] film.personal_film_appearance.person  ->  ['m.0v4mj0y', 'm.0v4ndsn', 'm.0v4mlsf', 'm.0v462vn', 'm.0v4mk_2'] ...
  [  9x] tv.tv_guest_role.actor  ->  ['m.0y7ls9m', 'm.0y7htk3', 'm.0kb00b3', 'm.0y7j8ry', 'm.0y7klbl'] ...
  [  9x] freebase.valuenotation.is_reviewed  ->  ['Parents', 'Date of birth', 'Children', 'Place of birth', 'Weight'] ...
  [  8x] common.topic.webpage  ->  ['m.0kg5v20', 'm.0bnsx2n', 'm.09wlf17', 'm.09ymk3w', 'm.09x22v7'] ...
  [  8x] film.person_or_entity_appearing_in_film.films  ->  ['m.0v4n9vx', 'm.0v4ncmr', 'm.0v464nl', 'm.0y7lnys', 'm.0107blsl'] ...
  [  5x] basketball.basketball_player_stats.player  ->  ['m.04qmm8m', 'm.04qcjh2', 'm.04qmsr4', 'm.04qp97c', 'm.04ql_x2']
  [  5x] people.person.profession  ->  ['Voice Actor', 'Basketball player', 'Television producer', 'Screenwriter', 'Athlete']
  [  4x] common.topic.image  ->  ['Lebron James', 'LeBron James 2', 'lebron-james.jpg', 'LeBron James']
  [  4x] common.webpage.topic  ->  ['m.09yjt3y', 'm.09yh16v', 'm.0b47jzs', 'm.0cvmhlb']
  [  4x] sports.sports_award_winner.awards  ->  ['m.04ynxp7', 'm.02kbccr', 'm.062txq3', 'm.0k0545f']
  [  3x] tv.tv_actor.guest_roles  ->  ['m.0y7k84w', 'm.09nb79p', 'm.0y7hr3h']
  [  3x] tv.tv_episode_segment.personal_appearances  ->  ['m.0khq_s7', 'm.0khq_qd', 'm.0kkj72n']
  [  3x] sports.sports_award.award_winner  ->  ['m.0k0543c', 'm.0w0h79l', 'm.04ynxph']
  [  3x] common.topic.notable_types  ->  ['TV Episode', 'Basketball Player', 'Book']
  [  3x] olympics.olympic_athlete.country  ->  ['m.0k8rqy4', 'm.04f9f2d', 'm.04fl3fv']
  [  3x] people.person.places_lived  ->  ['m.03pfl7k', 'm.0kfxz0z', 'm.03pr62x']
  [  3x] people.person.children  ->  ['LeBron James Jr.', 'Bryce Maximus James', 'Anthony McClelland']
  [  3x] sports.pro_athlete.teams  ->  ['m.011461z_', 'm.012z6mb1', 'm.0csn6xn']
  [  2x] tv.tv_personality.tv_regular_appearances  ->  ['m.0v45r6d', 'm.0ybfjfs']
  [  2x] tv.tv_segment_personal_appearance.person  ->  ['m.0khq_nf', 'm.0kjl_p5']
  [  2x] tv.tv_producer.tv_episodes_produced  ->  ['m.011x2jxp', 'm.011x2qqn']
  [  2x] base.schemastaging.athlete_salary.athlete  ->  ['m.0j_8xt1', 'm.0_r6zcj']
  [  2x] tv.tv_producer.programs_produced  ->  ['m.0t_92_c', 'm.011x17zz']
  [  2x] base.schemastaging.athlete_extra.salary  ->  ['m.0plswgw', 'm.0j2x60b']
  [  2x] music.recording.artist  ->  ['Intro', 'Outro']
  [  2x] sports.sports_team_roster.player  ->  ['m.02398d8', 'm.0z7hgc_']
  [  2x] basketball.basketball_player.position_s  ->  ['Small forward', 'Power forward']
  [  2x] book.written_work.author  ->  ['Shooting Stars', 'Lew Freedman']
  [  2x] common.topic.notable_for  ->  ['g.1256y2gpm', 'g.125509zk3']
  [  1x] business.sponsorship.sponsored_recipient  ->  ['m.03n9_n7']
  [  1x] basketball.basketball_position.players  ->  ['Point forward']
  [  1x] people.person.ethnicity  ->  ['African American']
  [  1x] people.person.spouse_s  ->  ['m.0y8c6k2']
  [  1x] tv.tv_segment_personal_appearance.segment  ->  ['m.0kfggqh']
  [  1x] tv.tv_actor.starring_roles  ->  ['m.0t_92x5']
  [  1x] base.popstra.celebrity.infidelity_participant  ->  ['m.063y076']
  [  1x] people.group_membership.member  ->  ['m.01146ms7']
  [  1x] tv.tv_writer.tv_programs  ->  ['m.0t_92_0']
  [  1x] people.marriage.spouse  ->  ['m.04g4z6t']
  [  1x] base.popstra.celebrity.friendship  ->  ['m.0h4xsfb']
  [  1x] sports.pro_sports_played.athlete  ->  ['m.0c3p_f6']
  [  1x] olympics.olympic_medal_honor.medalist  ->  ['m.0krvwc7']
  [  1x] basketball.basketball_player_career_stats.player  ->  ['m.04g4zm0']
  [  1x] common.image.size  ->  ['m.02f01qx']
  [  1x] book.written_work.subjects  ->  ['Meet Lebron James']
  [  1x] olympics.olympic_athlete.medals_won  ->  ['m.04fl3dr']
  [  1x] tv.tv_regular_personal_appearance.person  ->  ['m.0kfqxgn']
  [  1x] people.person.place_of_birth  ->  ['Akron']
  [  1x] tv.tv_program_guest.appeared_on  ->  ['m.0kfb_jk']
  [  1x] sports.sports_league_draft_pick.player  ->  ['m.04fl3dj']
  [  1x] people.person.parents  ->  ['Gloria Marie James']
  [  1x] film.film.executive_produced_by  ->  ['More than a Game']
  [  1x] education.education.student  ->  ['m.040qhv9']
  [  1x] base.saturdaynightlive.snl_host.episodes_hosted  ->  ['LeBron James/Kanye West']
  [  1x] people.person.nationality  ->  ['United States of America']
  [  1x] common.topic.article  ->  ['m.01jz6q']
  [  1x] freebase.valuenotation.has_no_value  ->  ['Siblings']
  [  1x] people.person.gender  ->  ['Male']
  [  1x] film.actor.film  ->  ['g.11bbrhyr4z']
  [  1x] base.schemastaging.person_extra.net_worth  ->  ['m.0j2x62m']

=== Incoming relations to 'LeBron James' (64 distinct relations) ===
  [ 26x] award.award_winner.awards_won  <-  ['m.0x0wvvk', 'm.0_qr6bw', 'm.0x0ww2n', 'm.0_qrm17', 'm.0yg0zky'] ...
  [ 23x] award.award_nominee.award_nominations  <-  ['m.0z7yzvr', 'm.0sgkpd0', 'm.0z5blfv', 'm.0sgl513', 'm.0z3sxnh'] ...
  [ 20x] award.award_nomination.award_nominee  <-  ['m.0z1n6dn', 'm.0_spmjw', 'm.0z3v44c', 'm.0115gb6f', 'm.010_xz3j'] ...
  [ 16x] award.award_honor.award_winner  <-  ['m.0_qr864', 'm.0_qvzz1', 'm.0yg0y_2', 'm.0_qtsk9', 'm.0yg0_0r'] ...
  [ 13x] film.personal_film_appearance.person  <-  ['m.0v4ndsn', 'm.0v4663b', 'm.0v4nckg', 'm.0v4mkf7', 'm.0v4mj0y'] ...
  [  9x] freebase.valuenotation.is_reviewed  <-  ['Date of birth', 'Gender', 'Country of nationality', 'Children', 'Parents'] ...
  [  9x] tv.tv_guest_role.actor  <-  ['m.0y7ls9m', 'm.0y7htk3', 'm.0kb00b3', 'm.0y7j8ry', 'm.0y7klbl'] ...
  [  8x] common.topic.webpage  <-  ['m.0kg5v20', 'm.0bnsx2n', 'm.09wlf17', 'm.09ymk3w', 'm.0b48_yp'] ...
  [  8x] film.person_or_entity_appearing_in_film.films  <-  ['m.0107blsl', 'm.0pc9rsr', 'm.0v4n9vx', 'm.0v4mp1x', 'm.0v4ncmr'] ...
  [  5x] people.person.profession  <-  ['Voice Actor', 'Basketball player', 'Athlete', 'Screenwriter', 'Television producer']
  [  5x] basketball.basketball_player_stats.player  <-  ['m.04qmm8m', 'm.04qcjh2', 'm.04qp97c', 'm.04qmsr4', 'm.04ql_x2']
  [  4x] common.webpage.topic  <-  ['m.09yjt3y', 'm.09yh16v', 'm.0b47jzs', 'm.0cvmhlb']
  [  4x] sports.sports_award_winner.awards  <-  ['m.04ynxp7', 'm.02kbccr', 'm.062txq3', 'm.0k0545f']
  [  3x] common.topic.notable_types  <-  ['Basketball Player', 'TV Episode', 'Book']
  [  3x] common.topic.image  <-  ['Lebron James', 'LeBron James 2', 'lebron-james.jpg']
  [  3x] tv.tv_actor.guest_roles  <-  ['m.0y7k84w', 'm.09nb79p', 'm.0y7hr3h']
  [  3x] sports.sports_award.award_winner  <-  ['m.04ynxph', 'm.0k0543c', 'm.0w0h79l']
  [  3x] tv.tv_episode_segment.personal_appearances  <-  ['m.0khq_s7', 'm.0khq_qd', 'm.0kkj72n']
  [  3x] olympics.olympic_athlete.country  <-  ['m.0k8rqy4', 'm.04f9f2d', 'm.04fl3fv']
  [  3x] people.person.places_lived  <-  ['m.03pfl7k', 'm.0kfxz0z', 'm.03pr62x']
  [  3x] people.person.children  <-  ['LeBron James Jr.', 'Anthony McClelland', 'Bryce Maximus James']
  [  3x] sports.pro_athlete.teams  <-  ['m.0csn6xn', 'm.012z6mb1', 'm.011461z_']
  [  2x] base.schemastaging.athlete_extra.salary  <-  ['m.0plswgw', 'm.0j2x60b']
  [  2x] tv.tv_personality.tv_regular_appearances  <-  ['m.0v45r6d', 'm.0ybfjfs']
  [  2x] tv.tv_segment_personal_appearance.person  <-  ['m.0khq_nf', 'm.0kjl_p5']
  [  2x] tv.tv_producer.tv_episodes_produced  <-  ['m.011x2qqn', 'm.011x2jxp']
  [  2x] basketball.basketball_player.position_s  <-  ['Small forward', 'Power forward']
  [  2x] sports.sports_team_roster.player  <-  ['m.02398d8', 'm.0z7hgc_']
  [  2x] base.schemastaging.athlete_salary.athlete  <-  ['m.0_r6zcj', 'm.0j_8xt1']
  [  2x] book.written_work.author  <-  ['Shooting Stars', 'Lew Freedman']
  [  2x] tv.tv_producer.programs_produced  <-  ['m.0t_92_c', 'm.011x17zz']
  [  2x] music.recording.artist  <-  ['Intro', 'Outro']
  [  2x] common.topic.notable_for  <-  ['g.1256y2gpm', 'g.125509zk3']
  [  1x] film.film.executive_produced_by  <-  ['More than a Game']
  [  1x] people.person.ethnicity  <-  ['African American']
  [  1x] sports.sports_league_draft_pick.player  <-  ['m.04fl3dj']
  [  1x] base.schemastaging.person_extra.net_worth  <-  ['m.0j2x62m']
  [  1x] people.person.spouse_s  <-  ['m.0y8c6k2']
  [  1x] basketball.basketball_position.players  <-  ['Point forward']
  [  1x] olympics.olympic_athlete.medals_won  <-  ['m.04fl3dr']
  [  1x] business.sponsorship.sponsored_recipient  <-  ['m.03n9_n7']
  [  1x] people.person.nationality  <-  ['United States of America']
  [  1x] olympics.olympic_medal_honor.medalist  <-  ['m.0krvwc7']
  [  1x] freebase.valuenotation.has_no_value  <-  ['Siblings']
  [  1x] tv.tv_actor.starring_roles  <-  ['m.0t_92x5']
  [  1x] people.marriage.spouse  <-  ['m.04g4z6t']
  [  1x] people.person.gender  <-  ['Male']
  [  1x] base.saturdaynightlive.snl_host.episodes_hosted  <-  ['LeBron James/Kanye West']
  [  1x] people.group_membership.member  <-  ['m.01146ms7']
  [  1x] sports.pro_sports_played.athlete  <-  ['m.0c3p_f6']
  [  1x] tv.tv_segment_personal_appearance.segment  <-  ['m.0kfggqh']
  [  1x] people.person.place_of_birth  <-  ['Akron']
  [  1x] people.person.parents  <-  ['Gloria Marie James']
  [  1x] base.popstra.celebrity.infidelity_participant  <-  ['m.063y076']
  [  1x] tv.tv_writer.tv_programs  <-  ['m.0t_92_0']
  [  1x] tv.tv_regular_personal_appearance.person  <-  ['m.0kfqxgn']
  [  1x] base.popstra.celebrity.friendship  <-  ['m.0h4xsfb']
  [  1x] basketball.basketball_player_career_stats.player  <-  ['m.04g4zm0']
  [  1x] common.image.size  <-  ['m.02f01qx']
  [  1x] book.written_work.subjects  <-  ['Meet Lebron James']
  [  1x] education.education.student  <-  ['m.040qhv9']
  [  1x] tv.tv_program_guest.appeared_on  <-  ['m.0kfb_jk']
  [  1x] common.topic.article  <-  ['m.01jz6q']
  [  1x] film.actor.film  <-  ['g.11bbrhyr4z']